// Code generated by sei-tendermint/internal/protoutils/wireguard_plugin. DO NOT EDIT.
package blocksync

import (
	runtime "github.com/sei-protocol/sei-chain/sei-tendermint/internal/protoutils/runtime"
	utils "github.com/sei-protocol/sei-chain/sei-tendermint/libs/utils"
	types "github.com/sei-protocol/sei-chain/sei-tendermint/proto/tendermint/types"
	reflect "reflect"
)

func init() {
	// Register the wireguard.Schema generated for tendermint.blocksync.BlockResponse.
	runtime.MustRegister[*BlockResponse](runtime.Schema{
		1: {Nested: utils.Some(reflect.TypeFor[*types.Block]())},
	})

	// Register the wireguard.Schema generated for tendermint.blocksync.Message.
	runtime.MustRegister[*Message](runtime.Schema{
		3: {Nested: utils.Some(reflect.TypeFor[*BlockResponse]())},
	})

}
