// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: confidentialtransfers/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgTransfer represents a message to send coins from one account to another.
type MsgTransfer struct {
	FromAddress        string          `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty" yaml:"from_address"`
	ToAddress          string          `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty" yaml:"to_address"`
	Denom              string          `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty" yaml:"denom"`
	FromAmountLo       *Ciphertext     `protobuf:"bytes,4,opt,name=from_amount_lo,json=fromAmountLo,proto3" json:"from_amount_lo,omitempty" yaml:"from_amount_lo"`
	FromAmountHi       *Ciphertext     `protobuf:"bytes,5,opt,name=from_amount_hi,json=fromAmountHi,proto3" json:"from_amount_hi,omitempty" yaml:"from_amount_hi"`
	ToAmountLo         *Ciphertext     `protobuf:"bytes,6,opt,name=to_amount_lo,json=toAmountLo,proto3" json:"to_amount_lo,omitempty" yaml:"to_amount_lo"`
	ToAmountHi         *Ciphertext     `protobuf:"bytes,7,opt,name=to_amount_hi,json=toAmountHi,proto3" json:"to_amount_hi,omitempty" yaml:"to_amount_hi"`
	RemainingBalance   *Ciphertext     `protobuf:"bytes,8,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty" yaml:"decryptable_balance"`
	DecryptableBalance string          `protobuf:"bytes,9,opt,name=decryptable_balance,json=decryptableBalance,proto3" json:"decryptable_balance,omitempty" yaml:"decryptable_balance"`
	Proofs             *TransferProofs `protobuf:"bytes,10,opt,name=proofs,proto3" json:"proofs,omitempty" yaml:"proofs"`
	Auditors           []*Auditor      `protobuf:"bytes,11,rep,name=auditors,proto3" json:"auditors,omitempty" yaml:"auditors"`
}

func (m *MsgTransfer) Reset()         { *m = MsgTransfer{} }
func (m *MsgTransfer) String() string { return proto.CompactTextString(m) }
func (*MsgTransfer) ProtoMessage()    {}
func (*MsgTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_34e86c2ca2c678f9, []int{0}
}
func (m *MsgTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransfer.Merge(m, src)
}
func (m *MsgTransfer) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransfer proto.InternalMessageInfo

// MsgSendResponse defines the Msg/Send response type.
type MsgTransferResponse struct {
}

func (m *MsgTransferResponse) Reset()         { *m = MsgTransferResponse{} }
func (m *MsgTransferResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferResponse) ProtoMessage()    {}
func (*MsgTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34e86c2ca2c678f9, []int{1}
}
func (m *MsgTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferResponse.Merge(m, src)
}
func (m *MsgTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferResponse proto.InternalMessageInfo

type Auditor struct {
	AuditorAddress                string                             `protobuf:"bytes,1,opt,name=auditor_address,json=auditorAddress,proto3" json:"auditor_address,omitempty" yaml:"address"`
	EncryptedTransferAmountLo     *Ciphertext                        `protobuf:"bytes,2,opt,name=encrypted_transfer_amount_lo,json=encryptedTransferAmountLo,proto3" json:"encrypted_transfer_amount_lo,omitempty" yaml:"encrypted_transfer_amount_lo"`
	EncryptedTransferAmountHi     *Ciphertext                        `protobuf:"bytes,3,opt,name=encrypted_transfer_amount_hi,json=encryptedTransferAmountHi,proto3" json:"encrypted_transfer_amount_hi,omitempty" yaml:"encrypted_transfer_amount_hi"`
	TransferAmountLoValidityProof *CiphertextValidityProof           `protobuf:"bytes,4,opt,name=transfer_amount_lo_validity_proof,json=transferAmountLoValidityProof,proto3" json:"transfer_amount_lo_validity_proof,omitempty" yaml:"transfer_amount_lo_validity_proof"`
	TransferAmountHiValidityProof *CiphertextValidityProof           `protobuf:"bytes,5,opt,name=transfer_amount_hi_validity_proof,json=transferAmountHiValidityProof,proto3" json:"transfer_amount_hi_validity_proof,omitempty" yaml:"transfer_amount_hi_validity_proof"`
	TransferAmountLoEqualityProof *CiphertextCiphertextEqualityProof `protobuf:"bytes,6,opt,name=transfer_amount_lo_equality_proof,json=transferAmountLoEqualityProof,proto3" json:"transfer_amount_lo_equality_proof,omitempty" yaml:"transfer_amount_lo_equality_proof"`
	TransferAmountHiEqualityProof *CiphertextCiphertextEqualityProof `protobuf:"bytes,7,opt,name=transfer_amount_hi_equality_proof,json=transferAmountHiEqualityProof,proto3" json:"transfer_amount_hi_equality_proof,omitempty" yaml:"transfer_amount_hi_equality_proof"`
}

func (m *Auditor) Reset()         { *m = Auditor{} }
func (m *Auditor) String() string { return proto.CompactTextString(m) }
func (*Auditor) ProtoMessage()    {}
func (*Auditor) Descriptor() ([]byte, []int) {
	return fileDescriptor_34e86c2ca2c678f9, []int{2}
}
func (m *Auditor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Auditor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Auditor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Auditor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auditor.Merge(m, src)
}
func (m *Auditor) XXX_Size() int {
	return m.Size()
}
func (m *Auditor) XXX_DiscardUnknown() {
	xxx_messageInfo_Auditor.DiscardUnknown(m)
}

var xxx_messageInfo_Auditor proto.InternalMessageInfo

func (m *Auditor) GetAuditorAddress() string {
	if m != nil {
		return m.AuditorAddress
	}
	return ""
}

func (m *Auditor) GetEncryptedTransferAmountLo() *Ciphertext {
	if m != nil {
		return m.EncryptedTransferAmountLo
	}
	return nil
}

func (m *Auditor) GetEncryptedTransferAmountHi() *Ciphertext {
	if m != nil {
		return m.EncryptedTransferAmountHi
	}
	return nil
}

func (m *Auditor) GetTransferAmountLoValidityProof() *CiphertextValidityProof {
	if m != nil {
		return m.TransferAmountLoValidityProof
	}
	return nil
}

func (m *Auditor) GetTransferAmountHiValidityProof() *CiphertextValidityProof {
	if m != nil {
		return m.TransferAmountHiValidityProof
	}
	return nil
}

func (m *Auditor) GetTransferAmountLoEqualityProof() *CiphertextCiphertextEqualityProof {
	if m != nil {
		return m.TransferAmountLoEqualityProof
	}
	return nil
}

func (m *Auditor) GetTransferAmountHiEqualityProof() *CiphertextCiphertextEqualityProof {
	if m != nil {
		return m.TransferAmountHiEqualityProof
	}
	return nil
}

// Message to be used in apply pending balance instruction/transaction
type MsgApplyPendingBalance struct {
	Address                        string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Denom                          string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	NewDecryptableAvailableBalance string `protobuf:"bytes,3,opt,name=new_decryptable_available_balance,json=newDecryptableAvailableBalance,proto3" json:"new_decryptable_available_balance,omitempty"`
}

func (m *MsgApplyPendingBalance) Reset()         { *m = MsgApplyPendingBalance{} }
func (m *MsgApplyPendingBalance) String() string { return proto.CompactTextString(m) }
func (*MsgApplyPendingBalance) ProtoMessage()    {}
func (*MsgApplyPendingBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_34e86c2ca2c678f9, []int{3}
}
func (m *MsgApplyPendingBalance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApplyPendingBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApplyPendingBalance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApplyPendingBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApplyPendingBalance.Merge(m, src)
}
func (m *MsgApplyPendingBalance) XXX_Size() int {
	return m.Size()
}
func (m *MsgApplyPendingBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApplyPendingBalance.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApplyPendingBalance proto.InternalMessageInfo

func (m *MsgApplyPendingBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgApplyPendingBalance) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgApplyPendingBalance) GetNewDecryptableAvailableBalance() string {
	if m != nil {
		return m.NewDecryptableAvailableBalance
	}
	return ""
}

type MsgApplyPendingBalanceResponse struct {
}

func (m *MsgApplyPendingBalanceResponse) Reset()         { *m = MsgApplyPendingBalanceResponse{} }
func (m *MsgApplyPendingBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgApplyPendingBalanceResponse) ProtoMessage()    {}
func (*MsgApplyPendingBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34e86c2ca2c678f9, []int{4}
}
func (m *MsgApplyPendingBalanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApplyPendingBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApplyPendingBalanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApplyPendingBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApplyPendingBalanceResponse.Merge(m, src)
}
func (m *MsgApplyPendingBalanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgApplyPendingBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApplyPendingBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApplyPendingBalanceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgTransfer)(nil), "seiprotocol.seichain.confidentialtransfers.MsgTransfer")
	proto.RegisterType((*MsgTransferResponse)(nil), "seiprotocol.seichain.confidentialtransfers.MsgTransferResponse")
	proto.RegisterType((*Auditor)(nil), "seiprotocol.seichain.confidentialtransfers.Auditor")
	proto.RegisterType((*MsgApplyPendingBalance)(nil), "seiprotocol.seichain.confidentialtransfers.MsgApplyPendingBalance")
	proto.RegisterType((*MsgApplyPendingBalanceResponse)(nil), "seiprotocol.seichain.confidentialtransfers.MsgApplyPendingBalanceResponse")
}

func init() { proto.RegisterFile("confidentialtransfers/tx.proto", fileDescriptor_34e86c2ca2c678f9) }

var fileDescriptor_34e86c2ca2c678f9 = []byte{
	// 863 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xbf, 0x6f, 0xfb, 0x44,
	0x14, 0x8f, 0x5b, 0xda, 0x24, 0x97, 0xd2, 0x6f, 0xeb, 0xb4, 0xe0, 0x46, 0x60, 0xa7, 0x87, 0x04,
	0x11, 0x82, 0x44, 0x6a, 0x11, 0x48, 0x61, 0xa8, 0xe2, 0x82, 0x14, 0x10, 0x11, 0x95, 0x85, 0x90,
	0x60, 0x89, 0x9c, 0xf8, 0x62, 0x9f, 0x70, 0x7c, 0xae, 0xed, 0xb4, 0x0d, 0x2b, 0x0c, 0x8c, 0x48,
	0x2c, 0x8c, 0x5d, 0x18, 0xd9, 0xd8, 0x98, 0x91, 0x18, 0x3b, 0x32, 0x59, 0xa8, 0x5d, 0x98, 0xfd,
	0x17, 0xa0, 0x9c, 0x7d, 0x8e, 0x9d, 0xb8, 0x3f, 0xd2, 0x7c, 0xdb, 0xcd, 0x77, 0xf7, 0xde, 0xe7,
	0xf3, 0x79, 0xef, 0xee, 0x3d, 0x3f, 0x20, 0xf6, 0x89, 0x35, 0xc0, 0x1a, 0xb2, 0x3c, 0xac, 0x9a,
	0x9e, 0xa3, 0x5a, 0xee, 0x00, 0x39, 0x6e, 0xc3, 0xbb, 0xa8, 0xdb, 0x0e, 0xf1, 0x08, 0xff, 0xae,
	0x8b, 0x30, 0xfd, 0xea, 0x13, 0xb3, 0xee, 0x22, 0xdc, 0x37, 0x54, 0x6c, 0xd5, 0x33, 0x9d, 0x2a,
	0x3b, 0x3a, 0xd1, 0x09, 0x35, 0x6e, 0x4c, 0xbe, 0x42, 0x84, 0x4a, 0x2d, 0x9b, 0xa1, 0xef, 0x8c,
	0x6d, 0x8f, 0xe8, 0x8e, 0x6a, 0x1b, 0xe3, 0xc8, 0xf2, 0x16, 0x2d, 0xdf, 0x7f, 0x17, 0x9e, 0xc3,
	0xdf, 0x0b, 0xa0, 0xd4, 0x71, 0xf5, 0xaf, 0xa2, 0x13, 0xbe, 0x09, 0x36, 0x06, 0x0e, 0x19, 0x76,
	0x55, 0x4d, 0x73, 0x90, 0xeb, 0x0a, 0x5c, 0x95, 0xab, 0x15, 0xe5, 0xd7, 0x03, 0x5f, 0x2a, 0x8f,
	0xd5, 0xa1, 0xd9, 0x84, 0xc9, 0x53, 0xa8, 0x94, 0x26, 0xcb, 0x56, 0xb8, 0xe2, 0x3f, 0x00, 0xc0,
	0x23, 0xb1, 0xe7, 0x0a, 0xf5, 0xdc, 0x0d, 0x7c, 0x69, 0x3b, 0xf4, 0x9c, 0x9e, 0x41, 0xa5, 0xe8,
	0x11, 0xe6, 0xf5, 0x36, 0x58, 0xd3, 0x90, 0x45, 0x86, 0xc2, 0x2a, 0x75, 0xd8, 0x0a, 0x7c, 0x69,
	0x23, 0x74, 0xa0, 0xdb, 0x50, 0x09, 0x8f, 0xf9, 0x73, 0xb0, 0x19, 0x72, 0x0f, 0xc9, 0xc8, 0xf2,
	0xba, 0x26, 0x11, 0x5e, 0xa9, 0x72, 0xb5, 0xd2, 0xc1, 0x87, 0xf5, 0x87, 0xa7, 0xb3, 0x7e, 0x8c,
	0x6d, 0x03, 0x39, 0x1e, 0xba, 0xf0, 0xe4, 0xbd, 0xc0, 0x97, 0x76, 0x93, 0x31, 0x31, 0x5c, 0xa8,
	0xd0, 0x14, 0xb4, 0xe8, 0xfa, 0x0b, 0x32, 0x4b, 0x6c, 0x60, 0x61, 0xed, 0x29, 0x88, 0x0d, 0x9c,
	0x22, 0x6e, 0x63, 0xfe, 0x14, 0x6c, 0x4c, 0x72, 0x16, 0xc7, 0xbb, 0xbe, 0x14, 0x6d, 0xe2, 0x0e,
	0x93, 0xa8, 0x50, 0x01, 0x1e, 0x89, 0x63, 0x4d, 0x51, 0x1a, 0x58, 0xc8, 0xbf, 0x7c, 0xca, 0x49,
	0x9c, 0x31, 0x65, 0x1b, 0xf3, 0x3f, 0x70, 0x60, 0xdb, 0x41, 0x43, 0x15, 0x5b, 0xd8, 0xd2, 0xbb,
	0x3d, 0xd5, 0x54, 0xad, 0x3e, 0x12, 0x0a, 0x4b, 0x11, 0x8b, 0x81, 0x2f, 0x55, 0xd8, 0x23, 0xa2,
	0x55, 0xa1, 0xf6, 0x4c, 0xc4, 0xc0, 0xa1, 0xb2, 0x15, 0x13, 0xca, 0xe1, 0x16, 0xff, 0x25, 0x28,
	0x67, 0x58, 0x0a, 0x45, 0xfa, 0x26, 0xef, 0x83, 0xe3, 0x13, 0xbb, 0x0c, 0x10, 0x81, 0x75, 0xdb,
	0x21, 0x64, 0xe0, 0x0a, 0x80, 0x86, 0xd2, 0x5c, 0x24, 0x14, 0x56, 0x8e, 0x27, 0x14, 0x41, 0xde,
	0x0e, 0x7c, 0xe9, 0xd5, 0x90, 0x3f, 0xc4, 0x84, 0x4a, 0x04, 0xce, 0x6b, 0xa0, 0xa0, 0x8e, 0x34,
	0xec, 0x11, 0xc7, 0x15, 0x4a, 0xd5, 0xd5, 0x5a, 0xe9, 0xe0, 0x70, 0x11, 0xa2, 0x56, 0xe8, 0x2b,
	0x97, 0x03, 0x5f, 0x7a, 0x11, 0x32, 0x30, 0x38, 0xa8, 0xc4, 0xc8, 0xcd, 0xc2, 0x4f, 0x97, 0x52,
	0xee, 0xbf, 0x4b, 0x29, 0x07, 0x77, 0x41, 0x39, 0xd1, 0x2e, 0x14, 0xe4, 0xda, 0xc4, 0x72, 0x11,
	0xfc, 0xb5, 0x08, 0xf2, 0x11, 0x16, 0xff, 0x31, 0x78, 0x11, 0x39, 0xce, 0x74, 0x11, 0x3e, 0xf0,
	0xa5, 0xcd, 0x88, 0x84, 0x35, 0x82, 0xcd, 0xc8, 0x94, 0x75, 0x83, 0x4b, 0x0e, 0xbc, 0x81, 0x2c,
	0x9a, 0x4d, 0xa4, 0x75, 0x99, 0xd0, 0x44, 0x11, 0xac, 0x2c, 0xf5, 0x30, 0xde, 0x09, 0x7c, 0xe9,
	0xad, 0x50, 0xc2, 0x5d, 0x2c, 0x50, 0xd9, 0x8b, 0x8f, 0x59, 0xac, 0x71, 0x8d, 0xdc, 0x2d, 0xd1,
	0xc0, 0xb4, 0x91, 0x3d, 0xb1, 0xc4, 0x49, 0x11, 0xdd, 0x26, 0xb1, 0x8d, 0xf9, 0x3f, 0x39, 0xb0,
	0x3f, 0x1f, 0x55, 0xf7, 0x4c, 0x35, 0xb1, 0x86, 0xbd, 0x71, 0x97, 0x3e, 0x9e, 0xa8, 0x7f, 0x1e,
	0x3f, 0x4e, 0xe7, 0xd7, 0x11, 0x16, 0x7d, 0xa2, 0xf2, 0x7b, 0x81, 0x2f, 0xd5, 0xa2, 0x4a, 0xbf,
	0x8f, 0x17, 0x2a, 0x6f, 0x7a, 0x33, 0x39, 0x4d, 0x81, 0x65, 0xaa, 0x37, 0xf0, 0xac, 0xfa, 0xb5,
	0x67, 0x51, 0x3f, 0xc7, 0x3b, 0xa7, 0xbe, 0x8d, 0xd3, 0xea, 0xff, 0xca, 0xce, 0x3d, 0x3a, 0x1d,
	0xa9, 0xe6, 0x54, 0x7d, 0xd8, 0xcb, 0x3b, 0x8f, 0x53, 0x3f, 0xfd, 0xfa, 0x34, 0x42, 0x7d, 0xc8,
	0x2d, 0xa4, 0x15, 0x64, 0xdc, 0x42, 0x0a, 0x2c, 0x33, 0x0e, 0x03, 0xcf, 0xc6, 0x91, 0x7f, 0xe6,
	0x38, 0xe6, 0x14, 0x64, 0xdc, 0x47, 0x0a, 0x0c, 0xfe, 0xc2, 0x81, 0xd7, 0x3a, 0xae, 0xde, 0xb2,
	0x6d, 0x73, 0x7c, 0x82, 0x2c, 0x2d, 0xd1, 0xf4, 0x05, 0x90, 0x4f, 0x75, 0x28, 0x85, 0x2d, 0xf9,
	0x1d, 0x36, 0x94, 0xd0, 0x29, 0x86, 0x8d, 0x20, 0x9f, 0x81, 0x7d, 0x0b, 0x9d, 0x77, 0x93, 0xff,
	0x00, 0xf5, 0x4c, 0xc5, 0x66, 0xea, 0x97, 0x41, 0xc7, 0x18, 0x45, 0xb4, 0xd0, 0xf9, 0x27, 0x53,
	0xbb, 0x16, 0x33, 0x8b, 0xa8, 0x61, 0x15, 0x88, 0xd9, 0xa2, 0x58, 0x4b, 0x3d, 0xf8, 0x63, 0x05,
	0xac, 0x76, 0x5c, 0x9d, 0xff, 0x91, 0x03, 0x85, 0x78, 0x3c, 0xfb, 0x68, 0x91, 0x44, 0x27, 0x1a,
	0x75, 0xe5, 0xe8, 0x91, 0x8e, 0x4c, 0x0e, 0xff, 0x1b, 0x07, 0xca, 0x59, 0x39, 0x94, 0x17, 0x04,
	0xce, 0xc0, 0xa8, 0x7c, 0xbe, 0x3c, 0x06, 0xd3, 0x29, 0x7f, 0xf3, 0xf7, 0xb5, 0xc8, 0x5d, 0x5d,
	0x8b, 0xdc, 0xbf, 0xd7, 0x22, 0xf7, 0xf3, 0x8d, 0x98, 0xbb, 0xba, 0x11, 0x73, 0xff, 0xdc, 0x88,
	0xb9, 0x6f, 0x8f, 0x74, 0xec, 0x19, 0xa3, 0x5e, 0xbd, 0x4f, 0x86, 0x0d, 0x17, 0xe1, 0xf7, 0x19,
	0x21, 0x5d, 0x50, 0xc6, 0xc6, 0x45, 0xe3, 0x96, 0xd1, 0x7d, 0x6c, 0x23, 0xb7, 0xb7, 0x4e, 0x3d,
	0x0e, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x38, 0x3b, 0xdc, 0xd3, 0xe0, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Transfer defines a method for sending coins from one account to another account.
	Transfer(ctx context.Context, in *MsgTransfer, opts ...grpc.CallOption) (*MsgTransferResponse, error)
	// ApplyPendingBalance defines a method for applying pending balance to an account.
	ApplyPendingBalance(ctx context.Context, in *MsgApplyPendingBalance, opts ...grpc.CallOption) (*MsgApplyPendingBalanceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Transfer(ctx context.Context, in *MsgTransfer, opts ...grpc.CallOption) (*MsgTransferResponse, error) {
	out := new(MsgTransferResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.confidentialtransfers.Msg/Transfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ApplyPendingBalance(ctx context.Context, in *MsgApplyPendingBalance, opts ...grpc.CallOption) (*MsgApplyPendingBalanceResponse, error) {
	out := new(MsgApplyPendingBalanceResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.confidentialtransfers.Msg/ApplyPendingBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Transfer defines a method for sending coins from one account to another account.
	Transfer(context.Context, *MsgTransfer) (*MsgTransferResponse, error)
	// ApplyPendingBalance defines a method for applying pending balance to an account.
	ApplyPendingBalance(context.Context, *MsgApplyPendingBalance) (*MsgApplyPendingBalanceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Transfer(ctx context.Context, req *MsgTransfer) (*MsgTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (*UnimplementedMsgServer) ApplyPendingBalance(ctx context.Context, req *MsgApplyPendingBalance) (*MsgApplyPendingBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPendingBalance not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.confidentialtransfers.Msg/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Transfer(ctx, req.(*MsgTransfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ApplyPendingBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApplyPendingBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApplyPendingBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.confidentialtransfers.Msg/ApplyPendingBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApplyPendingBalance(ctx, req.(*MsgApplyPendingBalance))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seiprotocol.seichain.confidentialtransfers.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfer",
			Handler:    _Msg_Transfer_Handler,
		},
		{
			MethodName: "ApplyPendingBalance",
			Handler:    _Msg_ApplyPendingBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "confidentialtransfers/tx.proto",
}

func (m *MsgTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Auditors) > 0 {
		for iNdEx := len(m.Auditors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Auditors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.Proofs != nil {
		{
			size, err := m.Proofs.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if len(m.DecryptableBalance) > 0 {
		i -= len(m.DecryptableBalance)
		copy(dAtA[i:], m.DecryptableBalance)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DecryptableBalance)))
		i--
		dAtA[i] = 0x4a
	}
	if m.RemainingBalance != nil {
		{
			size, err := m.RemainingBalance.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.ToAmountHi != nil {
		{
			size, err := m.ToAmountHi.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.ToAmountLo != nil {
		{
			size, err := m.ToAmountLo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.FromAmountHi != nil {
		{
			size, err := m.FromAmountHi.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.FromAmountLo != nil {
		{
			size, err := m.FromAmountLo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Auditor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Auditor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Auditor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TransferAmountHiEqualityProof != nil {
		{
			size, err := m.TransferAmountHiEqualityProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.TransferAmountLoEqualityProof != nil {
		{
			size, err := m.TransferAmountLoEqualityProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.TransferAmountHiValidityProof != nil {
		{
			size, err := m.TransferAmountHiValidityProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.TransferAmountLoValidityProof != nil {
		{
			size, err := m.TransferAmountLoValidityProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.EncryptedTransferAmountHi != nil {
		{
			size, err := m.EncryptedTransferAmountHi.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.EncryptedTransferAmountLo != nil {
		{
			size, err := m.EncryptedTransferAmountLo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuditorAddress) > 0 {
		i -= len(m.AuditorAddress)
		copy(dAtA[i:], m.AuditorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AuditorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgApplyPendingBalance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApplyPendingBalance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApplyPendingBalance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewDecryptableAvailableBalance) > 0 {
		i -= len(m.NewDecryptableAvailableBalance)
		copy(dAtA[i:], m.NewDecryptableAvailableBalance)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewDecryptableAvailableBalance)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgApplyPendingBalanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApplyPendingBalanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApplyPendingBalanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.FromAmountLo != nil {
		l = m.FromAmountLo.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.FromAmountHi != nil {
		l = m.FromAmountHi.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ToAmountLo != nil {
		l = m.ToAmountLo.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ToAmountHi != nil {
		l = m.ToAmountHi.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RemainingBalance != nil {
		l = m.RemainingBalance.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DecryptableBalance)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Proofs != nil {
		l = m.Proofs.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Auditors) > 0 {
		for _, e := range m.Auditors {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Auditor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuditorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EncryptedTransferAmountLo != nil {
		l = m.EncryptedTransferAmountLo.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EncryptedTransferAmountHi != nil {
		l = m.EncryptedTransferAmountHi.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TransferAmountLoValidityProof != nil {
		l = m.TransferAmountLoValidityProof.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TransferAmountHiValidityProof != nil {
		l = m.TransferAmountHiValidityProof.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TransferAmountLoEqualityProof != nil {
		l = m.TransferAmountLoEqualityProof.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TransferAmountHiEqualityProof != nil {
		l = m.TransferAmountHiEqualityProof.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgApplyPendingBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewDecryptableAvailableBalance)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgApplyPendingBalanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAmountLo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FromAmountLo == nil {
				m.FromAmountLo = &Ciphertext{}
			}
			if err := m.FromAmountLo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAmountHi", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FromAmountHi == nil {
				m.FromAmountHi = &Ciphertext{}
			}
			if err := m.FromAmountHi.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAmountLo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ToAmountLo == nil {
				m.ToAmountLo = &Ciphertext{}
			}
			if err := m.ToAmountLo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAmountHi", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ToAmountHi == nil {
				m.ToAmountHi = &Ciphertext{}
			}
			if err := m.ToAmountHi.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RemainingBalance == nil {
				m.RemainingBalance = &Ciphertext{}
			}
			if err := m.RemainingBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DecryptableBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DecryptableBalance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proofs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proofs == nil {
				m.Proofs = &TransferProofs{}
			}
			if err := m.Proofs.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auditors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Auditors = append(m.Auditors, &Auditor{})
			if err := m.Auditors[len(m.Auditors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Auditor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Auditor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Auditor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedTransferAmountLo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EncryptedTransferAmountLo == nil {
				m.EncryptedTransferAmountLo = &Ciphertext{}
			}
			if err := m.EncryptedTransferAmountLo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedTransferAmountHi", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EncryptedTransferAmountHi == nil {
				m.EncryptedTransferAmountHi = &Ciphertext{}
			}
			if err := m.EncryptedTransferAmountHi.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferAmountLoValidityProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferAmountLoValidityProof == nil {
				m.TransferAmountLoValidityProof = &CiphertextValidityProof{}
			}
			if err := m.TransferAmountLoValidityProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferAmountHiValidityProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferAmountHiValidityProof == nil {
				m.TransferAmountHiValidityProof = &CiphertextValidityProof{}
			}
			if err := m.TransferAmountHiValidityProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferAmountLoEqualityProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferAmountLoEqualityProof == nil {
				m.TransferAmountLoEqualityProof = &CiphertextCiphertextEqualityProof{}
			}
			if err := m.TransferAmountLoEqualityProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferAmountHiEqualityProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferAmountHiEqualityProof == nil {
				m.TransferAmountHiEqualityProof = &CiphertextCiphertextEqualityProof{}
			}
			if err := m.TransferAmountHiEqualityProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApplyPendingBalance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApplyPendingBalance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApplyPendingBalance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewDecryptableAvailableBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewDecryptableAvailableBalance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApplyPendingBalanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApplyPendingBalanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApplyPendingBalanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
