coverage:
  precision: 2
  round: down
  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project:
      default:
        threshold: 1% # allow this much decrease on project
        target: 50%
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  - "docs"
  - "*.md"
  - "*.rst"
  - "**/*pb*.go"
  - "tests/*"
  - "tests/**/*"
  - "x/**/test_common.go"
  - "scripts/"
  - "contrib"
