// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/gov/v1beta1/state.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	github_com_sei_protocol_sei_chain_sei_cosmos_types "github.com/sei-protocol/sei-chain/sei-cosmos/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TallyBoundary defines the electorate and update boundary for a tally round.
type TallyBoundary struct {
	LowerTime      time.Time             `protobuf:"bytes,1,opt,name=lower_time,json=lowerTime,proto3,stdtime" json:"lower_time"`
	UpperTime      time.Time             `protobuf:"bytes,2,opt,name=upper_time,json=upperTime,proto3,stdtime" json:"upper_time"`
	UpdateSequence uint64                `protobuf:"varint,3,opt,name=update_sequence,json=updateSequence,proto3" json:"update_sequence,omitempty"`
	Electorate     FrozenTallyElectorate `protobuf:"bytes,4,opt,name=electorate,proto3" json:"electorate"`
}

func (m *TallyBoundary) Reset()         { *m = TallyBoundary{} }
func (m *TallyBoundary) String() string { return proto.CompactTextString(m) }
func (*TallyBoundary) ProtoMessage()    {}
func (*TallyBoundary) Descriptor() ([]byte, []int) {
	return fileDescriptor_b559092a754c1c4c, []int{0}
}
func (m *TallyBoundary) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TallyBoundary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TallyBoundary.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TallyBoundary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TallyBoundary.Merge(m, src)
}
func (m *TallyBoundary) XXX_Size() int {
	return m.Size()
}
func (m *TallyBoundary) XXX_DiscardUnknown() {
	xxx_messageInfo_TallyBoundary.DiscardUnknown(m)
}

var xxx_messageInfo_TallyBoundary proto.InternalMessageInfo

// FrozenTallyElectorate defines the immutable validator and parameter state for a tally round.
type FrozenTallyElectorate struct {
	TotalBondedTokens github_com_sei_protocol_sei_chain_sei_cosmos_types.Int `protobuf:"bytes,1,opt,name=total_bonded_tokens,json=totalBondedTokens,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Int" json:"total_bonded_tokens"`
	TallyParams       TallyParams                                            `protobuf:"bytes,2,opt,name=tally_params,json=tallyParams,proto3" json:"tally_params"`
	Validators        []TallyValidator                                       `protobuf:"bytes,3,rep,name=validators,proto3" json:"validators"`
}

func (m *FrozenTallyElectorate) Reset()         { *m = FrozenTallyElectorate{} }
func (m *FrozenTallyElectorate) String() string { return proto.CompactTextString(m) }
func (*FrozenTallyElectorate) ProtoMessage()    {}
func (*FrozenTallyElectorate) Descriptor() ([]byte, []int) {
	return fileDescriptor_b559092a754c1c4c, []int{1}
}
func (m *FrozenTallyElectorate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FrozenTallyElectorate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FrozenTallyElectorate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FrozenTallyElectorate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrozenTallyElectorate.Merge(m, src)
}
func (m *FrozenTallyElectorate) XXX_Size() int {
	return m.Size()
}
func (m *FrozenTallyElectorate) XXX_DiscardUnknown() {
	xxx_messageInfo_FrozenTallyElectorate.DiscardUnknown(m)
}

var xxx_messageInfo_FrozenTallyElectorate proto.InternalMessageInfo

// TallyProgress defines the mutable cursor for an unfinished tally round.
type TallyProgress struct {
	Cursor     []byte `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	BoundaryId []byte `protobuf:"bytes,2,opt,name=boundary_id,json=boundaryId,proto3" json:"boundary_id,omitempty"`
	Expedited  bool   `protobuf:"varint,3,opt,name=expedited,proto3" json:"expedited,omitempty"`
}

func (m *TallyProgress) Reset()         { *m = TallyProgress{} }
func (m *TallyProgress) String() string { return proto.CompactTextString(m) }
func (*TallyProgress) ProtoMessage()    {}
func (*TallyProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_b559092a754c1c4c, []int{2}
}
func (m *TallyProgress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TallyProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TallyProgress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TallyProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TallyProgress.Merge(m, src)
}
func (m *TallyProgress) XXX_Size() int {
	return m.Size()
}
func (m *TallyProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_TallyProgress.DiscardUnknown(m)
}

var xxx_messageInfo_TallyProgress proto.InternalMessageInfo

// TallyOptionResults defines decimal totals by vote option.
type TallyOptionResults struct {
	Yes        github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,1,opt,name=yes,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"yes"`
	Abstain    github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,2,opt,name=abstain,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"abstain"`
	No         github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,3,opt,name=no,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"no"`
	NoWithVeto github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,4,opt,name=no_with_veto,json=noWithVeto,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"no_with_veto"`
}

func (m *TallyOptionResults) Reset()         { *m = TallyOptionResults{} }
func (m *TallyOptionResults) String() string { return proto.CompactTextString(m) }
func (*TallyOptionResults) ProtoMessage()    {}
func (*TallyOptionResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_b559092a754c1c4c, []int{3}
}
func (m *TallyOptionResults) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TallyOptionResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TallyOptionResults.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TallyOptionResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TallyOptionResults.Merge(m, src)
}
func (m *TallyOptionResults) XXX_Size() int {
	return m.Size()
}
func (m *TallyOptionResults) XXX_DiscardUnknown() {
	xxx_messageInfo_TallyOptionResults.DiscardUnknown(m)
}

var xxx_messageInfo_TallyOptionResults proto.InternalMessageInfo

// TallyValidatorAccumulator defines the mutable tally state for one frozen validator.
type TallyValidatorAccumulator struct {
	ObservedDelegatorShares github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,1,opt,name=observed_delegator_shares,json=observedDelegatorShares,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"observed_delegator_shares"`
	DelegatorResults        TallyOptionResults                                     `protobuf:"bytes,2,opt,name=delegator_results,json=delegatorResults,proto3" json:"delegator_results"`
	Vote                    []WeightedVoteOption                                   `protobuf:"bytes,3,rep,name=vote,proto3" json:"vote"`
}

func (m *TallyValidatorAccumulator) Reset()         { *m = TallyValidatorAccumulator{} }
func (m *TallyValidatorAccumulator) String() string { return proto.CompactTextString(m) }
func (*TallyValidatorAccumulator) ProtoMessage()    {}
func (*TallyValidatorAccumulator) Descriptor() ([]byte, []int) {
	return fileDescriptor_b559092a754c1c4c, []int{4}
}
func (m *TallyValidatorAccumulator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TallyValidatorAccumulator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TallyValidatorAccumulator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TallyValidatorAccumulator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TallyValidatorAccumulator.Merge(m, src)
}
func (m *TallyValidatorAccumulator) XXX_Size() int {
	return m.Size()
}
func (m *TallyValidatorAccumulator) XXX_DiscardUnknown() {
	xxx_messageInfo_TallyValidatorAccumulator.DiscardUnknown(m)
}

var xxx_messageInfo_TallyValidatorAccumulator proto.InternalMessageInfo

// VoteDelegationUpdate defines one deferred slash-induced delegation update.
type VoteDelegationUpdate struct {
	Voter     string                                                 `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Validator string                                                 `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Shares    github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,3,opt,name=shares,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"shares"`
	BlockTime time.Time                                              `protobuf:"bytes,4,opt,name=block_time,json=blockTime,proto3,stdtime" json:"block_time"`
	Cursor    []byte                                                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (m *VoteDelegationUpdate) Reset()         { *m = VoteDelegationUpdate{} }
func (m *VoteDelegationUpdate) String() string { return proto.CompactTextString(m) }
func (*VoteDelegationUpdate) ProtoMessage()    {}
func (*VoteDelegationUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_b559092a754c1c4c, []int{5}
}
func (m *VoteDelegationUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VoteDelegationUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VoteDelegationUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VoteDelegationUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteDelegationUpdate.Merge(m, src)
}
func (m *VoteDelegationUpdate) XXX_Size() int {
	return m.Size()
}
func (m *VoteDelegationUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteDelegationUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_VoteDelegationUpdate proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TallyBoundary)(nil), "cosmos.gov.v1beta1.TallyBoundary")
	proto.RegisterType((*FrozenTallyElectorate)(nil), "cosmos.gov.v1beta1.FrozenTallyElectorate")
	proto.RegisterType((*TallyProgress)(nil), "cosmos.gov.v1beta1.TallyProgress")
	proto.RegisterType((*TallyOptionResults)(nil), "cosmos.gov.v1beta1.TallyOptionResults")
	proto.RegisterType((*TallyValidatorAccumulator)(nil), "cosmos.gov.v1beta1.TallyValidatorAccumulator")
	proto.RegisterType((*VoteDelegationUpdate)(nil), "cosmos.gov.v1beta1.VoteDelegationUpdate")
}

func init() { proto.RegisterFile("cosmos/gov/v1beta1/state.proto", fileDescriptor_b559092a754c1c4c) }

var fileDescriptor_b559092a754c1c4c = []byte{
	// 759 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcd, 0x52, 0xe3, 0x46,
	0x10, 0xc7, 0x2d, 0xdb, 0x10, 0x3c, 0x76, 0x3e, 0x98, 0x90, 0xc4, 0x50, 0x94, 0xec, 0xf2, 0x21,
	0x21, 0x87, 0xc8, 0x05, 0xa9, 0x4a, 0xe5, 0x94, 0x4a, 0x1c, 0x92, 0x82, 0x4b, 0xa0, 0x04, 0x31,
	0x49, 0x2e, 0xca, 0x48, 0x6a, 0x64, 0x15, 0xf2, 0xb4, 0xa2, 0x19, 0x09, 0xcc, 0x53, 0x50, 0x95,
	0xe3, 0xbe, 0xc6, 0x3e, 0x04, 0x47, 0x8e, 0x5b, 0x7b, 0x60, 0x77, 0xe1, 0x0d, 0xf6, 0x05, 0x76,
	0x4b, 0xa3, 0x11, 0x86, 0x5a, 0x73, 0xa0, 0xe0, 0x36, 0xd3, 0xd3, 0xfd, 0x9b, 0xee, 0xd6, 0xbf,
	0x47, 0xc4, 0xf4, 0x50, 0x8c, 0x51, 0xf4, 0x03, 0xcc, 0xfa, 0xd9, 0xba, 0x0b, 0x92, 0xad, 0xf7,
	0x85, 0x64, 0x12, 0xac, 0x38, 0x41, 0x89, 0x94, 0x16, 0xe7, 0x56, 0x80, 0x99, 0xa5, 0xcf, 0x57,
	0xba, 0x33, 0x62, 0x02, 0xe0, 0x20, 0x42, 0x51, 0x44, 0xad, 0xac, 0xce, 0xf2, 0xc0, 0x4c, 0x9f,
	0x2e, 0x05, 0x18, 0xa0, 0x5a, 0xf6, 0xf3, 0x95, 0xb6, 0x76, 0x02, 0xc4, 0x20, 0x82, 0xbe, 0xda,
	0xb9, 0xe9, 0x61, 0x5f, 0x86, 0x63, 0x10, 0x92, 0x8d, 0xe3, 0xc2, 0xa1, 0xf7, 0x7f, 0x95, 0x7c,
	0xbc, 0xcf, 0xa2, 0x68, 0x32, 0xc0, 0x94, 0xfb, 0x2c, 0x99, 0xd0, 0x5f, 0x09, 0x89, 0xf0, 0x18,
	0x12, 0x27, 0x77, 0x6d, 0x1b, 0x5d, 0x63, 0xad, 0xb9, 0xb1, 0x62, 0x15, 0x1c, 0xab, 0xe4, 0x58,
	0xfb, 0x25, 0x67, 0xb0, 0x70, 0x7e, 0xd9, 0xa9, 0x9c, 0xbd, 0xea, 0x18, 0x76, 0x43, 0xc5, 0xe5,
	0x27, 0x39, 0x24, 0x8d, 0xe3, 0x12, 0x52, 0x7d, 0x08, 0x44, 0xc5, 0x29, 0xc8, 0x37, 0xe4, 0xd3,
	0x34, 0xf6, 0x99, 0x04, 0x47, 0xc0, 0x7f, 0x29, 0x70, 0x0f, 0xda, 0xb5, 0xae, 0xb1, 0x56, 0xb7,
	0x3f, 0x29, 0xcc, 0x7b, 0xda, 0x4a, 0x77, 0x08, 0x81, 0x08, 0x3c, 0x89, 0x09, 0x93, 0xd0, 0xae,
	0xab, 0xdb, 0xbe, 0xb5, 0x3e, 0x6c, 0xb2, 0xf5, 0x7b, 0x82, 0xa7, 0xc0, 0x55, 0xbd, 0xbf, 0xdd,
	0x04, 0x0c, 0xea, 0xf9, 0xe5, 0xf6, 0x2d, 0x44, 0xef, 0x59, 0x95, 0x7c, 0x31, 0xd3, 0x97, 0x72,
	0xf2, 0xb9, 0x44, 0xc9, 0x22, 0xc7, 0x45, 0xee, 0x83, 0xef, 0x48, 0x3c, 0x02, 0x2e, 0x54, 0x9b,
	0x1a, 0x83, 0x9f, 0x72, 0xd0, 0xcb, 0xcb, 0xce, 0x0f, 0x41, 0x28, 0x47, 0xa9, 0x6b, 0x79, 0x38,
	0xee, 0x0b, 0x08, 0xbf, 0x53, 0x05, 0x7b, 0x18, 0xa9, 0x8d, 0x37, 0x62, 0x21, 0x2f, 0x56, 0xc5,
	0xf7, 0x94, 0x93, 0x18, 0x84, 0xb5, 0xcd, 0xa5, 0xbd, 0xa8, 0xd0, 0x03, 0x45, 0xde, 0x57, 0x60,
	0xba, 0x45, 0x5a, 0x32, 0x4f, 0xc1, 0x89, 0x59, 0xc2, 0xc6, 0x42, 0xb7, 0xb2, 0x33, 0xab, 0x38,
	0x95, 0xea, 0xae, 0x72, 0xd3, 0x25, 0x35, 0xe5, 0xd4, 0x44, 0xb7, 0x08, 0xc9, 0x58, 0x14, 0xfa,
	0x4c, 0x62, 0x22, 0xda, 0xb5, 0x6e, 0x6d, 0xad, 0xb9, 0xd1, 0xbb, 0x97, 0x33, 0x2c, 0x5d, 0xcb,
	0xee, 0x4c, 0x63, 0x7b, 0x87, 0x5a, 0x32, 0xbb, 0x09, 0x06, 0x09, 0x08, 0x41, 0xbf, 0x24, 0xf3,
	0x5e, 0x9a, 0x08, 0x4c, 0x54, 0x1f, 0x5a, 0xb6, 0xde, 0xd1, 0x0e, 0x69, 0xba, 0x5a, 0x56, 0x4e,
	0xe8, 0xab, 0xdc, 0x5b, 0x36, 0x29, 0x4d, 0xdb, 0x3e, 0x5d, 0x25, 0x0d, 0x38, 0x89, 0xc1, 0x0f,
	0x25, 0xf8, 0xea, 0xdb, 0x2e, 0xd8, 0x53, 0x43, 0xef, 0x6d, 0x95, 0x50, 0x75, 0xd1, 0x4e, 0x2c,
	0x43, 0xe4, 0x36, 0x88, 0x34, 0x92, 0x82, 0xee, 0x92, 0xda, 0x04, 0x9e, 0xa2, 0xe5, 0x9b, 0xe0,
	0xd9, 0x39, 0x8a, 0xfe, 0x45, 0x3e, 0x62, 0xae, 0x90, 0x2c, 0xe4, 0x2a, 0xc7, 0xc7, 0x53, 0x4b,
	0x1c, 0xfd, 0x83, 0x54, 0x39, 0xaa, 0xca, 0x1e, 0x0f, 0xad, 0x72, 0xa4, 0xff, 0x92, 0x16, 0x47,
	0xe7, 0x38, 0x94, 0x23, 0x27, 0x03, 0x89, 0x4a, 0xeb, 0x8f, 0x27, 0x13, 0x8e, 0x07, 0xa1, 0x1c,
	0x0d, 0x41, 0x62, 0xef, 0x79, 0x95, 0x2c, 0xdf, 0x55, 0xc0, 0x2f, 0x9e, 0x97, 0x8e, 0xd3, 0x28,
	0x5f, 0xd2, 0x53, 0xb2, 0x8c, 0xae, 0x80, 0x24, 0x03, 0xdf, 0xf1, 0x21, 0x82, 0x20, 0xb7, 0x3a,
	0x62, 0xc4, 0x92, 0x27, 0xfb, 0x22, 0x5f, 0x95, 0x17, 0x6c, 0x96, 0xfc, 0x3d, 0x85, 0xa7, 0x7f,
	0x93, 0xc5, 0xe9, 0x95, 0x49, 0x21, 0x06, 0x3d, 0x0f, 0x5f, 0xdf, 0xab, 0xe3, 0x3b, 0xd2, 0xd1,
	0x5a, 0xfe, 0xec, 0x06, 0x53, 0x4a, 0xea, 0x67, 0x52, 0xcf, 0x50, 0x82, 0x9e, 0x8a, 0x99, 0xb4,
	0x03, 0x08, 0x83, 0x91, 0x04, 0x7f, 0x88, 0x12, 0x0a, 0xa8, 0xa6, 0xa9, 0xc8, 0xde, 0x3b, 0x83,
	0x2c, 0xe5, 0x47, 0x3a, 0xe9, 0x10, 0xf9, 0x9f, 0xea, 0x8d, 0xa2, 0x4b, 0x64, 0x2e, 0x77, 0x28,
	0x46, 0xa3, 0x61, 0x17, 0x9b, 0x5c, 0xf8, 0x37, 0x03, 0x55, 0x68, 0xce, 0x9e, 0x1a, 0xe8, 0x90,
	0xcc, 0xeb, 0x96, 0x3e, 0x8d, 0x72, 0x34, 0x2d, 0x7f, 0x95, 0xdd, 0x08, 0xbd, 0xa3, 0xe2, 0x55,
	0xae, 0x3f, 0xe4, 0x55, 0x56, 0x71, 0xea, 0x55, 0x9e, 0x0e, 0xfb, 0xdc, 0xed, 0x61, 0x1f, 0x0c,
	0xcf, 0xdf, 0x98, 0x95, 0xf3, 0x2b, 0xd3, 0xb8, 0xb8, 0x32, 0x8d, 0xd7, 0x57, 0xa6, 0x71, 0x76,
	0x6d, 0x56, 0x2e, 0xae, 0xcd, 0xca, 0x8b, 0x6b, 0xb3, 0xf2, 0xcf, 0x8f, 0x0f, 0x4a, 0xfd, 0x44,
	0xfd, 0xe4, 0x54, 0x01, 0xee, 0xbc, 0x72, 0xfd, 0xfe, 0x7d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f,
	0x50, 0x22, 0xad, 0x55, 0x07, 0x00, 0x00,
}

func (m *TallyBoundary) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TallyBoundary) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TallyBoundary) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Electorate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.UpdateSequence != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.UpdateSequence))
		i--
		dAtA[i] = 0x18
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.UpperTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.UpperTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintState(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LowerTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LowerTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintState(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FrozenTallyElectorate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FrozenTallyElectorate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FrozenTallyElectorate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.TallyParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.TotalBondedTokens.Size()
		i -= size
		if _, err := m.TotalBondedTokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TallyProgress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TallyProgress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TallyProgress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Expedited {
		i--
		if m.Expedited {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.BoundaryId) > 0 {
		i -= len(m.BoundaryId)
		copy(dAtA[i:], m.BoundaryId)
		i = encodeVarintState(dAtA, i, uint64(len(m.BoundaryId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Cursor) > 0 {
		i -= len(m.Cursor)
		copy(dAtA[i:], m.Cursor)
		i = encodeVarintState(dAtA, i, uint64(len(m.Cursor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TallyOptionResults) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TallyOptionResults) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TallyOptionResults) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.NoWithVeto.Size()
		i -= size
		if _, err := m.NoWithVeto.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.No.Size()
		i -= size
		if _, err := m.No.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Abstain.Size()
		i -= size
		if _, err := m.Abstain.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.Yes.Size()
		i -= size
		if _, err := m.Yes.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TallyValidatorAccumulator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TallyValidatorAccumulator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TallyValidatorAccumulator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vote) > 0 {
		for iNdEx := len(m.Vote) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vote[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.DelegatorResults.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.ObservedDelegatorShares.Size()
		i -= size
		if _, err := m.ObservedDelegatorShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VoteDelegationUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VoteDelegationUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VoteDelegationUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Cursor) > 0 {
		i -= len(m.Cursor)
		copy(dAtA[i:], m.Cursor)
		i = encodeVarintState(dAtA, i, uint64(len(m.Cursor)))
		i--
		dAtA[i] = 0x2a
	}
	n6, err6 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.BlockTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.BlockTime):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintState(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x22
	{
		size := m.Shares.Size()
		i -= size
		if _, err := m.Shares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintState(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintState(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TallyBoundary) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LowerTime)
	n += 1 + l + sovState(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.UpperTime)
	n += 1 + l + sovState(uint64(l))
	if m.UpdateSequence != 0 {
		n += 1 + sovState(uint64(m.UpdateSequence))
	}
	l = m.Electorate.Size()
	n += 1 + l + sovState(uint64(l))
	return n
}

func (m *FrozenTallyElectorate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalBondedTokens.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.TallyParams.Size()
	n += 1 + l + sovState(uint64(l))
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	return n
}

func (m *TallyProgress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Cursor)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.BoundaryId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Expedited {
		n += 2
	}
	return n
}

func (m *TallyOptionResults) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Yes.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.Abstain.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.No.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.NoWithVeto.Size()
	n += 1 + l + sovState(uint64(l))
	return n
}

func (m *TallyValidatorAccumulator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObservedDelegatorShares.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.DelegatorResults.Size()
	n += 1 + l + sovState(uint64(l))
	if len(m.Vote) > 0 {
		for _, e := range m.Vote {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	return n
}

func (m *VoteDelegationUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = m.Shares.Size()
	n += 1 + l + sovState(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.BlockTime)
	n += 1 + l + sovState(uint64(l))
	l = len(m.Cursor)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TallyBoundary) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TallyBoundary: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TallyBoundary: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowerTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LowerTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpperTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.UpperTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateSequence", wireType)
			}
			m.UpdateSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Electorate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Electorate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FrozenTallyElectorate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FrozenTallyElectorate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FrozenTallyElectorate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBondedTokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalBondedTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TallyParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TallyParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, TallyValidator{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TallyProgress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TallyProgress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TallyProgress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cursor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cursor = append(m.Cursor[:0], dAtA[iNdEx:postIndex]...)
			if m.Cursor == nil {
				m.Cursor = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoundaryId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BoundaryId = append(m.BoundaryId[:0], dAtA[iNdEx:postIndex]...)
			if m.BoundaryId == nil {
				m.BoundaryId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expedited", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Expedited = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TallyOptionResults) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TallyOptionResults: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TallyOptionResults: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Yes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Abstain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Abstain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field No", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.No.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoWithVeto", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NoWithVeto.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TallyValidatorAccumulator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TallyValidatorAccumulator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TallyValidatorAccumulator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedDelegatorShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObservedDelegatorShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorResults", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegatorResults.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vote = append(m.Vote, WeightedVoteOption{})
			if err := m.Vote[len(m.Vote)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VoteDelegationUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VoteDelegationUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VoteDelegationUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Shares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.BlockTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cursor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cursor = append(m.Cursor[:0], dAtA[iNdEx:postIndex]...)
			if m.Cursor == nil {
				m.Cursor = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
