project_name: price-feeder

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy -compat=1.17

builds:
  - main: ./
    id: "price-feeder"
    binary: price-feeder
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X price-feeder/cmd.Version={{ replace .Version "price-feeder/" "price-feeder-" }} -X price-feeder/cmd.Commit={{ .Commit }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ replace .Version "price-feeder/" "price-feeder-" }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README.md

release:
  disable: false
  name_template: "{{ .Tag }}"

checksum:
  name_template: 'SHA256SUMS-{{ replace .Version "price-feeder/" "price-feeder-" }}.txt'
  algorithm: sha256

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  skip: false
