gas_adjustment = 1.5
gas_prices = "0.00125usei"
enable_server = true
enable_voter = true

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[deviation_thresholds]]
base = "ETH"
threshold = "2"

[[deviation_thresholds]]
base = "BTC"
threshold = "2"

[[deviation_thresholds]]
base = "USDC"
threshold = "2"

[[deviation_thresholds]]
base = "USDT"
threshold = "2"

[[deviation_thresholds]]
base = "OSMO"
threshold = "2"

[[deviation_thresholds]]
base = "ATOM"
threshold = "2"

[[deviation_thresholds]]
base = "SEI"
threshold = "2"

[[currency_pairs]]
base = "ETH"
chain_denom = "ueth"
providers = [
  "huobi",
  "crypto",
  "coinbase",
  "kraken",
  "okx"
]
quote = "USDT"

[[currency_pairs]]
base = "BTC"
chain_denom = "ubtc"
providers = [
  "huobi",
  "kraken",
  "crypto",
  "coinbase",
  "okx",
]
quote = "USDT"

[[currency_pairs]]
base = "USDC"
chain_denom = "uusdc"
providers = [
  "huobi",
  "kraken",
  "okx",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "USDT"
chain_denom = "uusdt"
providers = [
  "kraken",
  "crypto",
  "coinbase",
]
quote = "USD"

[[currency_pairs]]
base = "OSMO"
chain_denom = "uosmo"
providers = [
  "huobi",
  "binance",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "OSMO"
chain_denom = "uosmo"
providers = [
  "coinbase"
]
quote = "USD"

[[currency_pairs]]
base = "SEI"
chain_denom = "usei"
providers = [
  "binance",
  "huobi",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "SEI"
chain_denom = "usei"
providers = [
  "kraken",
  "coinbase",
]
quote = "USD"

[[currency_pairs]]
base = "ATOM"
chain_denom = "uatom"
providers = [
  "huobi",
  "crypto",
  "binance",
  "gate",
  "okx",
]
quote = "USDT"

[account]
address = "<FEEDER_ADDR>"
chain_id = "<CHAIN_ID>"
validator = "<VALIDATOR_ADDR>"
prefix = "sei"

[keyring]
backend = "os"
dir = "/root/.sei"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable_hostname = true
enable_hostname_label = true
enable_service_label = true
enabled = true
global_labels = [["chain_id", "sei-chain"]]
service_name = "price-feeder"
prometheus_retention = 60

[[provider_endpoints]]
name = "binance"
rest = "https://api1.binance.com"
websocket = "stream.binance.com:9443"

# [[healthchecks]]
# url = "https://hc-ping.com/HEALTHCHECK-UUID"
# timeout = "5s"
