run:
  tests: false
  timeout: 10m
  build-tags:
    - codeanalysis

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - exportloopref
    - errcheck
    - goconst
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
    - misspell

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
    - text: "ST1016:"
      linters:
        - stylecheck
