version: "2"

run:
  tests: false
  timeout: 10m
  build-tags:
    - codeanalysis

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:" # Naming style
      linters:
        - stylecheck
    - text: "ST1016:" # Naming convention for receiver names
      linters:
        - stylecheck
