coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 60%
        threshold: 0.1% # allow this much decrease on project
        informational: true
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  - "docs"
  - "*.md"
  - "*.rst"
  - "**/*pb*.go"
  - "tests/**/*"
  - "x/**/test_common.go"
  - "scripts/"
  - "contrib"
  - "integration_test/**/*"
  - "docker/**/*"
