comment:
  behavior: default
  layout: reach,diff,flags,tree,betaprofiling
  require_changes:
    - 1

coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        target: 70.0
    project:
      default:
        target: auto
<<<<<<< HEAD
        threshold: 3% # allow this much decrease on project
=======
        threshold: 0.1
>>>>>>> origin/main
      sei-chain:
        flags:
          - sei-chain
        paths:
          - "sei-chain/**"
          - "!sei-cosmos/**"
          - "!sei-tendermint/**"
<<<<<<< HEAD
        flags:
          - sei-chain
      sei-cosmos:
        target: 35%
        paths:
          - "sei-cosmos/**"
        flags:
          - sei-cosmos
      sei-tendermint:
        target: 40%
        paths:
          - "sei-tendermint/**"
        flags:
          - sei-tendermint
    patch:
      default:
        target: auto

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default # update if exists else create new
  require_changes: true
=======
          - "!sei-wasmd/**"
          - "!sei-wasmvm/**"
>>>>>>> origin/main

ignore:
  - "**/docs/**/*"
  - "**/*.md"
  - "**/scripts/**/*"
  - "**/contrib/**/*"
  - "**/integration_test/**/*"
