coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 50%
        threshold: 0.1% # allow this much decrease on project
      # Per-module coverage targets
      sei-chain:
        paths:
          - "**"                      # include everything
        ignore:
          - "sei-cosmos/**"
          - "sei-tendermint/**"
          - "sei-wasmd/**"
          - "sei-wasmvm/**"
        flags:
          - sei-chain
      sei-cosmos:
        paths:
          - "sei-cosmos/**"
        flags:
          - sei-cosmos
      sei-tendermint:
        paths:
          - "sei-tendermint/**"
        flags:
          - sei-tendermint
      sei-wasmd:
        paths:
          - "sei-wasmd/**"
        flags:
          - sei-wasmd
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  # Common documentation and metadata
  - "**/docs/**"
  - "**/*.md"
  - "**/*.rst"

  # Generated protobuf files
  - "**/*pb*.go"
  - "**/*.pb.go"
  - "**/*.pb.gw.go"

  # Tests and test utilities
  - "**/tests/*"
  - "**/tests/**/*"
  - "**/integration_test/**/*"
  - "**/testutil/**"
  - "**/x/**/test_common.go"
  - "**/x/**/testdata/**"

  # Scripts, tooling, and contribution helpers
  - "**/scripts/**"
  - "**/contrib/**"
  - "**/docker/**"
  - "**/cmd/**"

  # Project-specific exclusions
  - "**/precompiles/*/legacy/**"
  - "**/cli/**"
  - "**/types/*.pb.go"
