coverage:
  precision: 2
  round: down
  status:
    # TODO: change project level coverage back to ~60% after we have a healthier repo
    project:
      default:
        target: 25%
        threshold: 0.1% # allow this much decrease on project
      # Per-module coverage targets
      sei-chain:
        target: 35%
        flags:
          - sei-chain
      sei-cosmos:
        target: 25%
        flags:
          - sei-cosmos
      sei-tendermint:
        target: 25%
        flags:
          - sei-tendermint
      sei-wasmd:
        target: 25%
        flags:
          - sei-wasmd
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  # Common documentation and metadata
  - "**/docs/**"
  - "**/*.md"
  - "**/*.rst"

  # Generated protobuf files
  - "**/*pb*.go"
  - "**/*.pb.go"
  - "**/*.pb.gw.go"

  # Tests and test utilities
  - "**/tests/*"
  - "**/tests/**/*"
  - "**/integration_test/**/*"
  - "**/testutil/**"
  - "**/x/**/test_common.go"
  - "**/x/**/testdata/**"

  # Scripts, tooling, and contribution helpers
  - "**/scripts/**"
  - "**/contrib/**"
  - "**/docker/**"
  - "**/cmd/**"

  # Project-specific exclusions
  - "**/precompiles/*/legacy/**"
  - "**/cli/**"
  - "**/types/*.pb.go"
