comment:
  behavior: default
  layout: reach,diff,flags,tree,betaprofiling
  require_changes:
    - 1

coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        target: 70.0
    project:
      default:
        target: auto
        threshold: 0.1
      sei-chain:
        flags:
          - sei-chain
        paths:
          - "sei-chain/**"
          - "!sei-cosmos/**"
          - "!sei-db/**"
          - "!sei-tendermint/**"
          - "!sei-wasmd/**"
          - "!sei-wasmvm/**"

ignore:
  - "**/docs/**/*"
  - "**/*.md"
  - "**/scripts/**/*"
  - "**/contrib/**/*"
  - "**/integration_test/**/*"
