coverage:
  precision: 2
  round: down
  status:
    # TODO: uncomment this when we have a healthier repo
    # project:
    #   default:
    #     target: 60%
    #     threshold: 0.1% # allow this much decrease on project
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  - "docs"
  - "*.md"
  - "*.rst"
  - "**/*pb*.go"
  - "tests/**/*"
  - "x/**/test_common.go"
  - "scripts/"
  - "contrib"
  - "integration_test/**/*"
  - "docker/**/*"
  - "testutil/**"
  - "precompiles/*/legacy/**"
  - "**/cli/**"
