coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 3% # allow this much decrease on project
      sei-chain:
        target: 40%
        paths:
          - "!sei-cosmos/**"
          - "!sei-tendermint/**"
        flags:
          - sei-chain
      sei-cosmos:
        target: 35%
        paths:
          - "sei-cosmos/**"
        flags:
          - sei-cosmos
      sei-tendermint:
        target: 40%
        paths:
          - "sei-tendermint/**"
        flags:
          - sei-tendermint
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  # Common documentation and metadata
  - "**/docs/**/*"
  - "**/*.md"
  - "**/*.rst"
  - "**/example/**/*"
  - "**/benchmark/**/*"

  # Generated protobuf files
  - "**/*.pb.go"
  - "**/*.pb.gw.go"

  # Tests and test utilities
  - "**/integration_test/**/*"
  - "**/testutil/**/*"
  - "**/x/**/test_common.go"
  - "**/x/**/testdata/**/*"

  # Scripts, tooling, and contribution helpers
  - "**/scripts/**/*"
  - "**/contrib/**/*"
  - "**/docker/**/*"

  # Project-specific exclusions
  - "precompiles/**/legacy/**/*"
  - "**/cli/**/*"
