coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 60%

comment:
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  - "docs"
  - "*.md"
  - "*.rst"
  - "**/*.pb.go"
  - "types/*.pb.go"
  - "tests/*"
  - "tests/**/*"
  - "x/**/*.pb.go"
  - "x/**/test_common.go"
  - "scripts/"
  - "contrib"
