build:
  main: './cmd/seid'
accounts:
  - name: alice
    coins: ['20000token', '200000000stake']
  - name: bob
    coins: ['10000token', '100000000stake']
validator:
  name: alice
  staked: '100000000stake'
client:
  openapi:
    path: 'docs/swagger-ui/swagger.yml'
  vuex:
    path: 'vue/src/store'
faucet:
  name: bob
  coins: ['5token', '100000stake']
