// Code generated by metricsgen. DO NOT EDIT.

package evidence

import (
	"github.com/prometheus/client_golang/prometheus"
	tmprometheus "github.com/sei-protocol/sei-chain/sei-tendermint/libs/utils/prometheus"
)

var Global = NewMetrics()

func init() {
	prometheus.MustRegister(
		Global.NumEvidence,
	)
}

func NewMetrics() *Metrics {
	return &Metrics{
		NumEvidence: tmprometheus.NewGaugeIntVec(prometheus.GaugeOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "num_evidence",
			Help:      "Number of pending evidence in the evidence pool.",
		}, nil),
	}
}

func (m *Metrics) NumEvidenceAt() *tmprometheus.GaugeInt {
	return m.NumEvidence.WithLabelValues()
}
