package configcli

import (
	"fmt"
	"sort"

	"github.com/sei-protocol/sei-chain/config/registry"
	"github.com/sei-protocol/sei-chain/config/seitoml"
)

// Generate renders the complete configuration for a node mode.
//
// Every declared key is written at the baseline for that mode, so the file is the whole picture of
// what the node runs at the moment it is generated.
//
// A written key is a commitment this binary never rewrites, and that applies to every key here.
// A generated node therefore does not follow a baseline that changes in a later release: it keeps
// the value that was current when the file was written, and regenerating is what moves it forward.
// The preamble says so in the file, because an operator reading it cannot otherwise tell the
// difference between a value they chose and one generate filled in.
func Generate(mode registry.Mode) (*seitoml.File, error) {
	if err := knownMode(mode); err != nil {
		return nil, err
	}
	resolved, err := registry.Resolve(mode)
	if err != nil {
		return nil, fmt.Errorf("resolve the baselines for mode %q: %w", mode, err)
	}
	if len(resolved.Keys) == 0 {
		return nil, fmt.Errorf("no section has registered a key, so generate would write an empty " +
			"file that reads as a node with nothing configured")
	}

	file, err := seitoml.New()
	if err != nil {
		return nil, err
	}
	file.SetPreamble(preamble(mode))

	// Sorted, so two runs of the same binary produce the same bytes and a diff between two nodes
	// compares configuration rather than map iteration order.
	for _, key := range sortedKeys(resolved) {
		if err := file.Set(key, resolved.Keys[key].Value); err != nil {
			return nil, fmt.Errorf("write %s: %w", key, err)
		}
	}
	return file, nil
}

// preamble is what the generated file says about itself.
//
// The mode is recorded because every value below was chosen for it, and a file generated for one
// mode running on a node started in another is not a configuration anyone intended.
func preamble(mode registry.Mode) []string {
	return []string{
		fmt.Sprintf(" Generated by seid config generate for a node running in %q mode.", mode),
		"",
		" Every key below is a written value, which this binary treats as your decision and",
		" never rewrites. That includes the ones generate filled in from its own defaults, so",
		" this node keeps these values across an upgrade even where a later release ships a",
		" different default. Run seid config generate again to move to the current defaults.",
		"",
		" The values here were chosen for the mode named above. Running the node in another",
		" mode does not re-resolve them.",
	}
}

// sortedKeys returns the resolved keys in a stable order.
func sortedKeys(resolved registry.Resolved) []string {
	keys := make([]string, 0, len(resolved.Keys))
	for k := range resolved.Keys {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// knownMode refuses a mode no section can produce a baseline for.
//
// Resolve would otherwise be asked for a mode the registry does not know, and a section's baseline
// function is free to answer for it with whatever its default branch returns. That would write a
// complete, plausible file for a mode no node runs.
func knownMode(mode registry.Mode) error {
	for _, m := range registry.Modes() {
		if m == mode {
			return nil
		}
	}
	return fmt.Errorf("%q is not a node mode; the modes are %v", mode, registry.Modes())
}
