package configtest

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// wiringRecordSuffix names the per-package record of which checks each section is wired to.
//
// Distinct from ".golden", which the two value records use. Those hold a snapshot of program output, so
// a diff in one means a value or a key name moved. This holds which checks are written, so a diff in it
// means coverage changed. The suffix is what tells a reader which of the two they are looking at.
//
// It also keeps the two apart on disk. Every record path is testdata/<name><suffix>, so a section named
// "wiring" resolves to testdata/wiring.golden while this file is testdata/wiring_coverage.txt, and no
// section name can collide with it.
const wiringRecordSuffix = "_coverage.txt"

// wiringRecordName is the stem the wiring record is filed under.
//
// One record per package rather than per section, because the thing being recorded is which checks a
// package calls, and that is a fact about the package. A per-section record would also need a call per
// section, and each of those calls would be as deletable as the calls it exists to protect.
const wiringRecordName = "wiring"

// CheckWiring records which checks each of this package's sections is wired to, and fails when the
// wiring changes without the record changing with it.
//
// This closes the one gap every other check in this package shares, which is that deleting a call to
// any of them is silent. A section wired to five checks and then to four still passes everything that
// remains, so coverage can be removed with nothing reporting it and the suite reading as it did before.
//
// This is the suite's coverage record, the third kind alongside the defaults record and the key-names
// record. It is compared exactly, the way go.sum is compared. Every line has to still be there, a line
// that disappeared is the alarm, and the file is regenerated by tooling rather than edited. It is not a
// lint baseline, which records violations to ignore, wants to shrink to nothing, and stays quiet when an
// entry disappears. This one stays complete, and an entry disappearing is the point.
//
// The wiring is read from the package's own source rather than recorded as calls happen. A run-time
// recorder would have to be consulted after every check had run, which makes the verdict depend on
// test order, and -shuffle=on is a run mode this suite is expected to survive. Reading the source is
// order-independent and gives the same answer under every mode.
//
// What it therefore establishes is that a call is written, not that it ran, and not even that it was
// built, since wiringOf ignores build tags on purpose. That is the right property here. The failure
// being prevented is a deleted line, and a call left in place but never reached is a far more visible
// edit than a line that is simply gone.
//
// The record is a set of pairs, so it says which checks a section is covered by rather than how many
// times. Two calls to the same check naming the same section collapse to one line, and deleting either
// leaves the record unchanged. Every pair in the tree is a single call today, so nothing is currently
// outside this, but a section that acquires a second call to one check acquires a deletion this cannot
// report.
//
// Call it once per package. Deleting that call is the one deletion this cannot catch, which is why
// testutil/configtest's own suite asserts that every package calling a check calls it too, and asserts
// the converse that every coverage record has such a package behind it. Between them a deleted call, a
// deleted CheckWiring, and a whole package's checks deleted at once all report.
func CheckWiring(t testing.TB) {
	t.Helper()

	got, err := wiringOf(".")
	if err != nil {
		t.Fatalf("read this package's wiring: %v", err)
	}
	if len(got) == 0 {
		t.Fatal("no configtest checks were found in this package, so the wiring record would be " +
			"empty and would assert nothing. CheckWiring reads the package in the working directory, " +
			"which for a test is the package's own directory.")
	}
	if slices.ContainsFunc(got, func(pair string) bool { return strings.HasPrefix(pair, notALiteral) }) {
		t.Fatalf("this package calls a check whose section argument is not a string literal, so the " +
			"record cannot name it.\n\nWrite the section name at the call site. A constant does not " +
			"resolve here, and neither does a table's loop variable: every such call collapses to one " +
			"row, so deleting any of them leaves this record unchanged and stops protecting the rest.")
	}

	path := goldenFilePath(t, wiringRecordName, wiringRecordSuffix)
	record := strings.Join(append(wiringRecordHeader(), got...), "\n")

	// goldenUpdateRequested rather than recordRewriteInProgress, which is what every other writer in
	// this package uses. The CI refusal lives inside writeGolden, so a writer needs no guard of its own
	// and one here would be a second guard at a call site the choke point already covers.
	if goldenUpdateRequested() {
		writeGolden(t, wiringRecordName, path, record)
		return
	}

	raw, err := os.ReadFile(path) //nolint:gosec // testdata/wiring_coverage.txt; the file name is validated by goldenFilePath
	if err != nil {
		t.Fatalf("cannot read %s (%v).\nThis file records which checks each section in this package "+
			"is wired to, so that removing a check fails rather than passing quietly. Create it with "+
			"`go test ./<pkg>/ -run TestWiringMatchesTheRecord -update` and read what it lists.",
			path, err)
	}
	if record == recordText(raw) {
		return
	}
	t.Fatalf("this package's wiring no longer matches %s.\n%s\n"+
		"A line that disappeared is a check that was removed, which is the one edit the remaining "+
		"checks cannot report. If the removal is deliberate, regenerate the record with `-update` so "+
		"the lost coverage appears in the diff.", path, wiringDiff(recordText(raw), record))
}

// wiringRecordHeader says what the record is, so it reads without the reader having to find this
// file.
//
// Part of the recorded text rather than a comment the comparison strips, because a header that is
// not compared is a header someone can edit into something untrue.
func wiringRecordHeader() []string {
	return []string{
		"# Code generated by TestWiringMatchesTheRecord. DO NOT EDIT.",
		"# The coverage record. Which checks cover each configuration section in this package, one",
		"# tab-separated (section, check) pair per line, read from this package's own test files.",
		"# Compared exactly, the way go.sum is. A line that disappears is a check that was deleted,",
		"# which is the one edit the remaining checks cannot report. Repeat calls collapse to one line,",
		"# so this records which checks cover a section rather than how many times.",
		"# Regenerate with `go test ./<pkg>/ -run TestWiringMatchesTheRecord -update` and read the diff.",
		"",
	}
}

// wiringOf returns the sorted "section\tcheck" pairs the package in dir calls.
//
// Every _test.go file in the directory is parsed whatever its build tags say, and that is deliberate.
// Honoring build constraints would make the record differ between a Linux CI runner and a darwin
// development machine, so a record generated on one could not be compared on the other. Reading the
// directory and parsing each file spells that choice out. go/parser.ParseDir does the same thing, but
// the standard library deprecates it precisely for ignoring build tags, so relying on it would leave
// this behaviour resting on a deprecated call's side effect rather than on a decision.
func wiringOf(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	seen := make(map[string]bool)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, entry.Name()), nil, 0)
		if err != nil {
			return nil, err
		}
		for _, pair := range wiringIn(file) {
			seen[pair] = true
		}
	}

	pairs := make([]string, 0, len(seen))
	for pair := range seen {
		pairs = append(pairs, pair)
	}
	sort.Strings(pairs)
	return pairs, nil
}

// wiringIn collects the checks one file calls, with the section each names.
//
// Matched on the call's shape rather than on a list of check names, so a check added to this package
// later is recorded without anyone remembering to extend a list here.
func wiringIn(file *ast.File) []string {
	local, ok := configtestPackageName(file)
	if !ok {
		return nil
	}

	var pairs []string
	ast.Inspect(file, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		check, ok := configtestCheckName(call, local)
		if !ok {
			return true
		}
		pairs = append(pairs, sectionOf(call, check)+"\t"+check)
		return true
	})
	return pairs
}

// configtestPackageName returns the name a file binds this package to, and whether it imports it.
//
// Read from the file's imports rather than assumed to be "configtest", because an aliased import would
// otherwise match nothing and the file would contribute no pairs. That failure is silent in the one
// place it matters most. A new package that aliases the import and never calls CheckWiring records no
// pairs, so the bootstrap check in this package's own suite classifies it as unwired and never asks it
// for a record, which is exactly the coverage-removed-with-nothing-reporting-it case this file exists
// to prevent.
//
// A dot-import is reported as absent. Its calls carry no package receiver, so nothing here could match
// them whatever this returned, and a file importing this package that way contributes no pairs and
// fails CheckWiring's empty-set check rather than passing quietly.
func configtestPackageName(file *ast.File) (string, bool) {
	for _, spec := range file.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil || !strings.HasSuffix(path, "testutil/configtest") {
			continue
		}
		if spec.Name == nil {
			return "configtest", true
		}
		if spec.Name.Name == "." || spec.Name.Name == "_" {
			return "", false
		}
		return spec.Name.Name, true
	}
	return "", false
}

// configtestCheckName reports the name of the configtest check a call invokes, where local is the name
// the calling file binds this package to.
func configtestCheckName(call *ast.CallExpr, local string) (string, bool) {
	selector, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", false
	}
	pkg, ok := selector.X.(*ast.Ident)
	if !ok || pkg.Name != local || !strings.HasPrefix(selector.Sel.Name, "Check") {
		return "", false
	}
	// CheckWiring records the others; recording itself would make the file describe its own presence
	// rather than the coverage it protects.
	if selector.Sel.Name == "CheckWiring" {
		return "", false
	}
	return selector.Sel.Name, true
}

// packageWide names the checks that cover a package rather than one of its sections.
//
// Such a check carries no section to read, so it is recorded under a stable label rather than refused.
// Nothing is missing: the check is wired, and what it is wired to is the package. Named explicitly, so a
// check that ought to carry a section cannot join this set by accident.
var packageWide = map[string]bool{
	// Judges every experimental declaration, defect, checker and tombstone in the binary at once.
	"CheckExperimentalDeclarations": true,
}

// packageWideLabel is the section column for a check that covers the package.
const packageWideLabel = "(package)"

// sectionOf returns the section name a check call names.
//
// Every check takes the section as its second argument, after the testing.TB or testing.F, and that is
// a contract on any check added later. configtestCheckName deliberately matches every Check* rather
// than a fixed list, so a new check is recorded without anyone editing this file, and a new check that
// puts its section anywhere but the second argument would be recorded under the placeholder below.
//
// A call whose section is not a literal is refused rather than recorded, because the record cannot name
// it. Two such calls collapse to one row, so deleting either leaves the record unchanged and the check
// silently stops protecting them. A placeholder row also hid a section spelled two ways in one package,
// which is the sort of thing this record exists to make visible.
//
// The record pins the literal text of the argument, so it will faithfully pin a wrong one. A package that
// spells one section two ways shows up as two sections, which is a thing to notice in the diff rather than
// a thing this can decide.
func sectionOf(call *ast.CallExpr, check string) string {
	if packageWide[check] {
		return packageWideLabel
	}
	const sectionArg = 1
	if len(call.Args) <= sectionArg {
		return "(no section argument)"
	}
	literal, ok := call.Args[sectionArg].(*ast.BasicLit)
	if !ok || literal.Kind != token.STRING {
		return notALiteral
	}
	name, err := strconv.Unquote(literal.Value)
	if err != nil {
		return notALiteral
	}
	return name
}

// notALiteral marks a call whose section this cannot read. CheckWiring refuses it rather than recording it.
const notALiteral = "(section not a literal)"

// wiringDiff reports which pairs were lost and which were added, so a failure names the change rather
// than printing two lists for a reader to compare by eye.
func wiringDiff(want, got string) string {
	inGot := make(map[string]bool)
	for _, line := range strings.Split(got, "\n") {
		inGot[line] = true
	}
	inWant := make(map[string]bool)
	for _, line := range strings.Split(want, "\n") {
		inWant[line] = true
	}

	var b strings.Builder
	for _, line := range strings.Split(want, "\n") {
		if line != "" && !inGot[line] {
			fmt.Fprintf(&b, "  removed: %s\n", strings.ReplaceAll(line, "\t", " -> "))
		}
	}
	for _, line := range strings.Split(got, "\n") {
		if line != "" && !inWant[line] {
			fmt.Fprintf(&b, "  added:   %s\n", strings.ReplaceAll(line, "\t", " -> "))
		}
	}
	return strings.TrimRight(b.String(), "\n")
}
