{
 "title": "CryptoSim",
 "description": "A DB microbenchmark, workload is a simulation of ERC20 crypto-transfer traffic.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Blocks / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(cryptosim_blocks_finalized_total[5m])",
     "legendFormat": "Blocks / Second"
    }
   ]
  },
  {
   "title": "Block Finalization Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(cryptosim_block_finalization_latency_seconds_bucket[5m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(cryptosim_block_finalization_latency_seconds_bucket[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, rate(cryptosim_block_finalization_latency_seconds_bucket[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(cryptosim_block_finalization_latency_seconds_sum[5m]) / rate(cryptosim_block_finalization_latency_seconds_count[5m])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Commits / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(cryptosim_db_commits_total[5m])",
     "legendFormat": "Blocks / Second"
    }
   ]
  },
  {
   "title": "DB Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(cryptosim_db_commit_latency_seconds_bucket[5m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(cryptosim_db_commit_latency_seconds_bucket[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, rate(cryptosim_db_commit_latency_seconds_bucket[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(cryptosim_db_commit_latency_seconds_sum[5m]) / rate(cryptosim_db_commit_latency_seconds_count[5m])",
     "legendFormat": "average"
    }
   ]
  }
 ]
}