// Code generated by metricsgen. DO NOT EDIT.

package giga

import (
	"github.com/prometheus/client_golang/prometheus"
	tmprometheus "github.com/sei-protocol/sei-chain/sei-tendermint/libs/utils/prometheus"
)

var Global = newMetrics()

func init() {
	prometheus.MustRegister(
		Global.fetch,
		Global.serve,
	)
}

func newMetrics() *metrics {
	return &metrics{
		fetch: tmprometheus.NewCounterIntVec(prometheus.CounterOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "fetch",
			Help:      "Client fetches by resource and reason, including ok.",
		}, []string{"resource", "reason"}),
		serve: tmprometheus.NewCounterIntVec(prometheus.CounterOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "serve",
			Help:      "Server replies that did not return the requested object.",
		}, []string{"resource", "reason"}),
	}
}

func (m *metrics) fetchAt(resource string, reason string) *tmprometheus.CounterInt {
	return m.fetch.WithLabelValues(resource, reason)
}

func (m *metrics) serveAt(resource string, reason string) *tmprometheus.CounterInt {
	return m.serve.WithLabelValues(resource, reason)
}
