// Code generated by metricsgen. DO NOT EDIT.

package state

import (
	"github.com/prometheus/client_golang/prometheus"
	tmprometheus "github.com/sei-protocol/sei-chain/sei-tendermint/libs/utils/prometheus"
)

var Global = NewMetrics()

func init() {
	prometheus.MustRegister(
		Global.BlockProcessingTime,
		Global.ConsensusParamUpdates,
		Global.ValidatorSetUpdates,
		Global.ApplicationCommitTime,
		Global.UpdateMempoolTime,
		Global.FinalizeBlockLatency,
		Global.SaveBlockResponseLatency,
		Global.SaveBlockLatency,
		Global.PruneBlockLatency,
		Global.FireEventsLatency,
		Global.ProposerPriorityHash,
		Global.ProposerPriorityHashHeight,
	)
}

func NewMetrics() *Metrics {
	return &Metrics{
		BlockProcessingTime: tmprometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "block_processing_time",
			Help:      "Time between BeginBlock and EndBlock.",
			Buckets:   prometheus.ExponentialBucketsRange(0.01, 10, 10),
		}, nil),
		ConsensusParamUpdates: tmprometheus.NewCounterIntVec(prometheus.CounterOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "consensus_param_updates",
			Help:      "Number of consensus parameter updates returned by the application since process start.",
		}, nil),
		ValidatorSetUpdates: tmprometheus.NewCounterIntVec(prometheus.CounterOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "validator_set_updates",
			Help:      "Number of validator set updates returned by the application since process start.",
		}, nil),
		ApplicationCommitTime: tmprometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "application_commit_time",
			Help:      "ApplicationCommitTime measures how long it takes to commit application state",
			Buckets:   prometheus.DefBuckets,
		}, nil),
		UpdateMempoolTime: tmprometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "update_mempool_time",
			Help:      "UpdateMempoolTime measures how long it takes to update mempool after committing, including reCheckTx",
			Buckets:   prometheus.DefBuckets,
		}, nil),
		FinalizeBlockLatency: tmprometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "finalize_block_latency",
			Help:      "FinalizeBlockLatency measures how long it takes to run abci FinalizeBlock",
			Buckets:   prometheus.ExponentialBucketsRange(0.01, 10, 10),
		}, nil),
		SaveBlockResponseLatency: tmprometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "save_block_response_latency",
			Help:      "SaveBlockResponseLatency measures how long it takes to run save the FinalizeBlockRes",
			Buckets:   prometheus.ExponentialBucketsRange(0.01, 10, 10),
		}, nil),
		SaveBlockLatency: tmprometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "save_block_latency",
			Help:      "SaveBlockLatency measure how long it takes to save the block",
			Buckets:   prometheus.ExponentialBucketsRange(0.01, 10, 10),
		}, nil),
		PruneBlockLatency: tmprometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "prune_block_latency",
			Help:      "PruneBlockLatency measures how long it takes to prune block from blockstore",
			Buckets:   prometheus.ExponentialBucketsRange(0.01, 10, 10),
		}, nil),
		FireEventsLatency: tmprometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "fire_events_latency",
			Help:      "FireEventsLatency measures how long it takes to fire events for indexing",
			Buckets:   prometheus.ExponentialBucketsRange(0.01, 10, 10),
		}, nil),
		ProposerPriorityHash: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "proposer_priority_hash",
			Help:      "ProposerPriorityHash encodes the first 6 bytes of the hash of the current validator set's proposer priorities as a float64 value. Exported periodically (every proposerPriorityHashInterval heights) for operator visibility; divergence between validators at the same ProposerPriorityHashHeight indicates corrupted ProposerPriority state. Paired with ProposerPriorityHashHeight so operators can correlate.",
		}, nil),
		ProposerPriorityHashHeight: tmprometheus.NewGaugeIntVec(prometheus.GaugeOpts{
			Namespace: MetricsNamespace,
			Subsystem: MetricsSubsystem,
			Name:      "proposer_priority_hash_height",
			Help:      "ProposerPriorityHashHeight is the block height at which the most recent ProposerPriorityHash was computed. Operators comparing hashes across validators should only compare samples at the same height.",
		}, nil),
	}
}

func (m *Metrics) BlockProcessingTimeAt() *tmprometheus.Histogram {
	return m.BlockProcessingTime.WithLabelValues()
}

func (m *Metrics) ConsensusParamUpdatesAt() *tmprometheus.CounterInt {
	return m.ConsensusParamUpdates.WithLabelValues()
}

func (m *Metrics) ValidatorSetUpdatesAt() *tmprometheus.CounterInt {
	return m.ValidatorSetUpdates.WithLabelValues()
}

func (m *Metrics) ApplicationCommitTimeAt() *tmprometheus.Histogram {
	return m.ApplicationCommitTime.WithLabelValues()
}

func (m *Metrics) UpdateMempoolTimeAt() *tmprometheus.Histogram {
	return m.UpdateMempoolTime.WithLabelValues()
}

func (m *Metrics) FinalizeBlockLatencyAt() *tmprometheus.Histogram {
	return m.FinalizeBlockLatency.WithLabelValues()
}

func (m *Metrics) SaveBlockResponseLatencyAt() *tmprometheus.Histogram {
	return m.SaveBlockResponseLatency.WithLabelValues()
}

func (m *Metrics) SaveBlockLatencyAt() *tmprometheus.Histogram {
	return m.SaveBlockLatency.WithLabelValues()
}

func (m *Metrics) PruneBlockLatencyAt() *tmprometheus.Histogram {
	return m.PruneBlockLatency.WithLabelValues()
}

func (m *Metrics) FireEventsLatencyAt() *tmprometheus.Histogram {
	return m.FireEventsLatency.WithLabelValues()
}

func (m *Metrics) ProposerPriorityHashAt() prometheus.Gauge {
	return m.ProposerPriorityHash.WithLabelValues()
}

func (m *Metrics) ProposerPriorityHashHeightAt() *tmprometheus.GaugeInt {
	return m.ProposerPriorityHashHeight.WithLabelValues()
}
