// Code generated by sei-tendermint/internal/protoutils/wireguard_plugin. DO NOT EDIT.
package store

import (
	runtime "github.com/sei-protocol/sei-chain/sei-tendermint/internal/protoutils/runtime"
)

func init() {
	// Register the wireguard.Schema generated for tendermint.store.BlockStoreState.
	runtime.MustRegister[*BlockStoreState](runtime.Schema{
		1: {MaxCount: 1},
		2: {MaxCount: 1},
	})

}
