{
 "title": "BlockSim",
 "description": "A BlockDB microbenchmark, workload is a simulation of block and transaction write traffic.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocks / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(blocksim_blocks_written_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(blocksim_transactions_written_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(blocksim_bytes_written_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prune Calls / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(blocksim_prune_calls_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush Calls / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(blocksim_flush_calls_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Main Thread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Time Spent",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocksim_main_thread_phase_duration_seconds_total[$__rate_interval])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Time Spent Per Block (amortized)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocksim_main_thread_phase_duration_seconds_total[$__rate_interval])\n/ on() group_left()\nrate(blocksim_blocks_written_total[$__rate_interval])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Time Spent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(blocksim_main_thread_phase_duration_seconds_total[$__rate_interval])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Time Spent Per Block (amortized)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(blocksim_main_thread_phase_duration_seconds_total[$__rate_interval])\n/ on() group_left()\nrate(blocksim_blocks_written_total[$__rate_interval])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Block State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lowest Block Height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "blocksim_lowest_block_height", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Highest Block Height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "blocksim_highest_block_height", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Blocks On Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "blocksim_highest_block_height-blocksim_lowest_block_height",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Size (Config)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "blocksim_block_size_bytes", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resident Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Heap Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Average GC Pause",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum[$__rate_interval]) / rate(go_gc_duration_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "go_goroutines", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "go_threads", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data On Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "blocksim_data_dir_size_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Data Growth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "deriv(blocksim_data_dir_size_bytes[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Available Disk Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "blocksim_data_dir_available_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Log Dir Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "blocksim_log_dir_size_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "process_open_fds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bytes Per Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "blocksim_data_dir_size_bytes / (blocksim_highest_block_height - blocksim_lowest_block_height + 1)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O (Linux only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(blocksim_process_read_bytes_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(blocksim_process_write_bytes_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Read IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(blocksim_process_read_count_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(blocksim_process_write_count_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "blocksim_uptime_seconds", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}