package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"go.opentelemetry.io/otel/sdk/trace"

	"github.com/sei-protocol/sei-chain/cmd/seid/cmd/configmanager"
	"github.com/sei-protocol/sei-chain/config/registry"
	"github.com/sei-protocol/sei-chain/sei-cosmos/server"
	"github.com/sei-protocol/sei-chain/testutil/configtest"
)

// whatANodeWithNoFileRuns is what each diverging key resolves to for a node that has no configuration file
// of its own, and lets the boot make one.
//
// A declared value is what the init command writes for a kind of node. That command is not the only thing
// in this binary that writes this file: a node started without one gets it generated by the boot instead,
// and the two do not agree. These are the keys where they differ, with what the second one produces.
//
// Held as text because the two sides carry different Go types for the same key often enough that comparing
// values would be comparing shapes. What matters is which keys disagree and what a node gets instead.
var whatANodeWithNoFileRuns = map[string]string{
	"p2p.recv-rate":    "5120000",
	"p2p.send-rate":    "5120000",
	"proxy-app":        "",
	"tx-index.indexer": "[kv]",
}

// whyEachMatters says what a node gets, and it is the reason each row is measured rather than described.
var whyEachMatters = map[string]string{
	"p2p.recv-rate": "the ceiling on what one connection may pull, four times lower than the declared " +
		"value, so a node adopting a file generated by the other writer would have it raised",
	"p2p.send-rate": "the same ceiling in the other direction",
	"proxy-app": "the address of the application the node talks to, which the boot assigns and then a " +
		"bound flag's empty default overwrites inside the same function",
	"tx-index.indexer": "whether the node indexes transactions. The boot's writer applies none of the " +
		"rules that vary a setting by kind of node, so a validator that let it generate this file " +
		"indexes every transaction, which is what the init command writes for a node that serves queries " +
		"and the opposite of what it writes for a validator",
}

// TestTheDivergencesFromAGeneratedFileAreTheRecordedOnes measures what a comment would only claim.
//
// The init command and the boot both generate this file and they disagree, so a declared value is what one
// of them writes and not simply what a generated file carries. Which keys those are is measured here rather
// than described, because a key that starts diverging fails and so does one that stops.
//
// Driven through a real boot with no configuration file of its own and no sei.toml, so nothing is delivered
// and what the node holds is purely what the boot generated.
func TestTheDivergencesFromAGeneratedFileAreTheRecordedOnes(t *testing.T) {
	configtest.Isolate(t)
	generated := whatTheBootGenerates(t)

	resolved, err := registry.Resolve(registry.ModeValidator, registry.Sources{})
	if err != nil {
		t.Fatalf("Resolve: %v", err)
	}

	var measured []string
	for key, got := range generated {
		declared, declares := resolved.Values[key]
		if !declares {
			continue
		}
		if fmt.Sprint(declared) == got {
			if _, listed := whatANodeWithNoFileRuns[key]; listed {
				t.Errorf("%s no longer diverges, both sides being %v. Take it off the record, so the "+
					"record stays the set of keys the two generators state differently", key, declared)
			}
			continue
		}
		measured = append(measured, key)
		want, listed := whatANodeWithNoFileRuns[key]
		switch {
		case !listed:
			t.Errorf("%s is declared as %v and a node that let the boot generate its file runs %q, and "+
				"nothing records that. %s", key, declared, got, whyEachMatters[key])
		case want != got:
			t.Errorf("%s is recorded as running %q and runs %q", key, want, got)
		}
	}

	sort.Strings(measured)
	if len(measured) != len(whatANodeWithNoFileRuns) {
		t.Errorf("measured %d divergences and %d are recorded: %v",
			len(measured), len(whatANodeWithNoFileRuns), measured)
	}
}

// whatTheBootGenerates returns what a node holds for every declared key of the decoded sections, having
// started with no configuration file of its own.
func whatTheBootGenerates(t *testing.T) map[string]string {
	t.Helper()
	home := configtest.NewHome(t)
	if err := os.MkdirAll(filepath.Join(home.Root, "config"), 0o750); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	cmd := server.StartCmd(nil, home.Root, []trace.TracerProviderOption{})
	if err := cmd.Flags().Set("home", home.Root); err != nil {
		t.Fatalf("set --home: %v", err)
	}
	ctx, err := runManager(t, configmanager.SeiConfigManager{}, cmd)
	if err != nil {
		t.Fatalf("the boot was refused: %v", err)
	}
	if ctx.Config == nil {
		t.Fatal("the boot produced no node configuration")
	}

	var keys []string
	for name := range registry.DecodedSections() {
		section, ok := registry.Lookup(name)
		if !ok {
			continue
		}
		keys = append(keys, section.Keys...)
	}
	return configmanager.DescribeForTest(ctx.Config, keys)
}
