syntax = "proto3";

package ibc.core.client.v1;

import "cosmos/upgrade/v1beta1/upgrade.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "google/protobuf/any.proto";

option go_package = "github.com/sei-protocol/sei-chain/app/retiredibc/gov";

// ClientUpdateProposal is the retired governance proposal for replacing a
// frozen client with a substitute client.
message ClientUpdateProposal {
  option (gogoproto.goproto_getters) = false;
  option (cosmos_proto.implements_interface) = "cosmos.gov.v1beta1.Content";

  string title = 1;
  string description = 2;
  string subject_client_id = 3 [(gogoproto.moretags) = "yaml:\"subject_client_id\""];
  string substitute_client_id = 4 [(gogoproto.moretags) = "yaml:\"substitute_client_id\""];
}

// UpgradeProposal is the retired governance proposal for an IBC breaking
// upgrade.
message UpgradeProposal {
  option (gogoproto.goproto_getters) = false;
  option (gogoproto.goproto_stringer) = false;
  option (gogoproto.equal) = true;
  option (cosmos_proto.implements_interface) = "cosmos.gov.v1beta1.Content";

  string title = 1;
  string description = 2;
  cosmos.upgrade.v1beta1.Plan plan = 3 [(gogoproto.nullable) = false];
  google.protobuf.Any upgraded_client_state = 4 [(gogoproto.moretags) = "yaml:\"upgraded_client_state\""];
}
