global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sei-localnet'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'sei-node-0:26660'
          - 'sei-node-1:26660'
          - 'sei-node-2:26660'
          - 'sei-node-3:26660'
    scrape_interval: 5s
