// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tokenfactory/gov.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AddCreatorsToDenomFeeWhitelistProposal struct {
	Title       string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title" yaml:"title"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description" yaml:"description"`
	CreatorList []string `protobuf:"bytes,3,rep,name=creatorList,proto3" json:"creator_list" yaml:"creator_list"`
}

func (m *AddCreatorsToDenomFeeWhitelistProposal) Reset() {
	*m = AddCreatorsToDenomFeeWhitelistProposal{}
}
func (*AddCreatorsToDenomFeeWhitelistProposal) ProtoMessage() {}
func (*AddCreatorsToDenomFeeWhitelistProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc5220110f821b0b, []int{0}
}
func (m *AddCreatorsToDenomFeeWhitelistProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddCreatorsToDenomFeeWhitelistProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddCreatorsToDenomFeeWhitelistProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddCreatorsToDenomFeeWhitelistProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCreatorsToDenomFeeWhitelistProposal.Merge(m, src)
}
func (m *AddCreatorsToDenomFeeWhitelistProposal) XXX_Size() int {
	return m.Size()
}
func (m *AddCreatorsToDenomFeeWhitelistProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCreatorsToDenomFeeWhitelistProposal.DiscardUnknown(m)
}

var xxx_messageInfo_AddCreatorsToDenomFeeWhitelistProposal proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddCreatorsToDenomFeeWhitelistProposal)(nil), "seiprotocol.seichain.tokenfactory.AddCreatorsToDenomFeeWhitelistProposal")
}

func init() { proto.RegisterFile("tokenfactory/gov.proto", fileDescriptor_cc5220110f821b0b) }

var fileDescriptor_cc5220110f821b0b = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x31, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0x2f, 0x16, 0x85, 0xa6, 0x9d, 0xa2, 0x48, 0x75, 0xc8, 0xd5, 0x80, 0x52, 0x10, 0x93,
	0x41, 0x70, 0xe8, 0x66, 0x15, 0x5d, 0x14, 0x4a, 0x11, 0x04, 0x17, 0x49, 0xd3, 0x67, 0x7a, 0x98,
	0xe6, 0x85, 0xdc, 0x53, 0xec, 0x37, 0x70, 0x74, 0x74, 0xec, 0xc7, 0xe9, 0xd8, 0xd1, 0xe9, 0x90,
	0x76, 0x91, 0x8e, 0xf9, 0x02, 0x4a, 0x2f, 0x0a, 0xe7, 0xf6, 0xde, 0xef, 0xfe, 0xbf, 0xe3, 0xf1,
	0x9e, 0xbd, 0x4d, 0xf8, 0x08, 0xe9, 0x43, 0x18, 0x11, 0xe6, 0xe3, 0x20, 0xc6, 0x67, 0x3f, 0xcb,
	0x91, 0xd0, 0xd9, 0x93, 0x20, 0x74, 0x15, 0x61, 0xe2, 0x4b, 0x10, 0xd1, 0x30, 0x14, 0xa9, 0x6f,
	0x86, 0x77, 0xb7, 0x62, 0x8c, 0x51, 0x67, 0x82, 0x55, 0x55, 0x8a, 0xde, 0xb7, 0x65, 0x1f, 0x9c,
	0x0e, 0x06, 0x67, 0x39, 0x84, 0x84, 0xb9, 0xbc, 0xc1, 0x73, 0x48, 0x71, 0x74, 0x01, 0x70, 0x3b,
	0x14, 0x04, 0x89, 0x90, 0xd4, 0xcd, 0x31, 0x43, 0x19, 0x26, 0x4e, 0x60, 0xaf, 0x93, 0xa0, 0x04,
	0x1a, 0x56, 0xd3, 0x6a, 0x55, 0x3b, 0x3b, 0x4b, 0xc5, 0x4b, 0x50, 0x28, 0x5e, 0x1f, 0x87, 0xa3,
	0xa4, 0xed, 0xe9, 0xd6, 0xeb, 0x95, 0xd8, 0xb9, 0xb4, 0x6b, 0x03, 0x90, 0x51, 0x2e, 0x32, 0x12,
	0x98, 0x36, 0xd6, 0xb4, 0xb6, 0xbf, 0x54, 0xdc, 0xc4, 0x85, 0xe2, 0x4e, 0x29, 0x1b, 0xd0, 0xeb,
	0x99, 0x11, 0xe7, 0xda, 0xae, 0x45, 0xe5, 0x80, 0x57, 0x42, 0x52, 0xa3, 0xd2, 0xac, 0xb4, 0xaa,
	0x9d, 0xc3, 0xa9, 0xe2, 0x6c, 0xa9, 0x78, 0xfd, 0xf7, 0xe9, 0x7e, 0x35, 0x6c, 0xa1, 0xf8, 0x66,
	0xf9, 0x9b, 0x49, 0xbd, 0x9e, 0xe9, 0xb7, 0xeb, 0xaf, 0x13, 0xce, 0xde, 0x27, 0x9c, 0x7d, 0x4d,
	0x38, 0xeb, 0x74, 0xa7, 0x73, 0xd7, 0x9a, 0xcd, 0x5d, 0xeb, 0x73, 0xee, 0x5a, 0x6f, 0x0b, 0x97,
	0xcd, 0x16, 0x2e, 0xfb, 0x58, 0xb8, 0xec, 0xee, 0x24, 0x16, 0x34, 0x7c, 0xea, 0xfb, 0x11, 0x8e,
	0x02, 0x09, 0xe2, 0xe8, 0x6f, 0xc1, 0xba, 0xd1, 0x1b, 0x0e, 0x5e, 0x82, 0x7f, 0x07, 0xa1, 0x71,
	0x06, 0xb2, 0xbf, 0xa1, 0x83, 0xc7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x12, 0x0e, 0x1e,
	0xad, 0x01, 0x00, 0x00,
}

func (m *AddCreatorsToDenomFeeWhitelistProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddCreatorsToDenomFeeWhitelistProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddCreatorsToDenomFeeWhitelistProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatorList) > 0 {
		for iNdEx := len(m.CreatorList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CreatorList[iNdEx])
			copy(dAtA[i:], m.CreatorList[iNdEx])
			i = encodeVarintGov(dAtA, i, uint64(len(m.CreatorList[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGov(dAtA []byte, offset int, v uint64) int {
	offset -= sovGov(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AddCreatorsToDenomFeeWhitelistProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	if len(m.CreatorList) > 0 {
		for _, s := range m.CreatorList {
			l = len(s)
			n += 1 + l + sovGov(uint64(l))
		}
	}
	return n
}

func sovGov(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGov(x uint64) (n int) {
	return sovGov(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AddCreatorsToDenomFeeWhitelistProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGov
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddCreatorsToDenomFeeWhitelistProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddCreatorsToDenomFeeWhitelistProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorList = append(m.CreatorList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGov(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGov
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGov(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGov
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGov
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGov
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGov
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGov
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGov
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGov        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGov          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGov = fmt.Errorf("proto: unexpected end of group")
)
