coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 60%
        threshold: 1% # allow this much decrease on project
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  - "*.md"
  - "*.rst"
  - "**/*pb*.go"
  - "tests/**/*"
  - "benchmark/"