name: AI Assistant
on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]
  pull_request_review:
    types: [ submitted ]
jobs:
  assistant:
    # See: https://github.com/sei-protocol/uci/releases/tag/v0.0.18
    uses: sei-protocol/uci/.github/workflows/ai-assistant.yml@be869659dad9a0ca5b5f2da126c0b5e7fa842535
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    secrets: inherit
    with:
      # See: https://github.com/sei-protocol/uci/releases/tag/v0.0.18
      uci-ref: be869659dad9a0ca5b5f2da126c0b5e7fa842535
      allowed-team: 'sei-protocol/sei-core'
