name: AI Assistant
on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]
jobs:
  assistant:
    # See: https://github.com/sei-protocol/uci/releases/tag/v0.0.19
    uses: sei-protocol/uci/.github/workflows/ai-assistant.yml@eb65d6d3f967c661f6af91cfac599fd355445f71
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    secrets: inherit
    with:
      # See: https://github.com/sei-protocol/uci/releases/tag/v0.0.19
      uci-ref: eb65d6d3f967c661f6af91cfac599fd355445f71
      allowed-team: 'sei-protocol/sei-core'
