name: AI Assistant
on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]
  pull_request_review:
    types: [ submitted ]
jobs:
  assistant:
    # See: https://github.com/sei-protocol/uci/releases/tag/v0.0.12
    uses: sei-protocol/uci/.github/workflows/ai-assistant.yml@258d2c3216d54872b33ac07430d23c847fc239ca
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    secrets: inherit
    with:
      # See: https://github.com/sei-protocol/uci/releases/tag/v0.0.12
      uci-ref: 258d2c3216d54872b33ac07430d23c847fc239ca
      allowed-team: 'sei-protocol/sei-core'
