name: Attribution & Authorship Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  attribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run attribution tests
        run: pytest tests/github_helpers_test.py --maxfail=1 --disable-warnings --tb=short

      - name: Upload commit author map artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: commit-author-map
          path: data/commit_author_map.json
          if-no-files-found: ignore
