name: Buf
on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    name: Check
    runs-on: ubuntu-latest
    steps:
        # See: https://github.com/actions/checkout/releases/tag/v7.0.0
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: bufbuild/buf-action@v1
        with:
          version: 1.58.0