name: CI – Integration & Contracts

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  # ---------- Build & Test Kin Contracts ----------
  contracts:
    name: Build & Test Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: |
          forge install foundry-rs/forge-std@v1.8.2 --no-commit
          forge install OpenZeppelin/openzeppelin-contracts@v5.0.2 --no-commit

      - name: Build contracts
        run: |
          forge --version
          forge build --evm-version=prague

      - name: Run Forge tests
        run: |
          forge test -vvv --evm-version=prague

  # ---------- Slinky Integration Tests ----------
  slinky:
    name: Slinky Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            slinky:
              - 'scripts/modules/slinky_test/**'
              - 'x/slinky/**'

      - uses: actions/setup-go@v5
        if: steps.filter.outputs.slinky == 'true'
        with:
          go-version: 1.21

      - name: Run Slinky Integration Tests
        if: steps.filter.outputs.slinky == 'true'
        run: scripts/modules/slinky_test/run_slinky_test.sh

  # ---------- x402 Settlement Check ----------
  x402:
    name: x402 Settlement Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: No-op confirmation
        run: echo "x402 settlement check: OK"
