final-check:
  name: ✅ Keeper CI Verdict
  needs: [tests]
  if: always()
  runs-on: ubuntu-latest
  steps:
    - name: Install GitHub CLI
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gh jq

    - name: Confirm All Test Shards Passed
      run: |
        failed=$(gh run view ${{ github.run_id }} \
          --json jobs \
          --jq '.jobs[] | select(.conclusion == "failure") | .name' | wc -l)

        if [[ "$failed" -gt 0 ]]; then
          echo "❌ $failed job(s) failed."
          exit 1
        else
          echo "✅ All test shards passed."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
