name: Claim Rewards

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes

jobs:
  claim:
    runs-on: ubuntu-latest

    env:
      RPC_URL: ${{ secrets.SEI_RPC_URL }}
      PRIVATE_KEY: ${{ secrets.x402_mnemonic }}
      REWARD_DISTRIBUTOR: "0x28BF6D71b6Dc837F56F5afbF1F4A46AaC0B1f31E"
      REWARD_USER: "0xb2b297eF9449aa0905bC318B3bd258c4804BAd98"

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install
        working-directory: tools/rewards

      - name: 🚀 Run live reward claim
        run: |
          node tools/rewards/autoClaimer.mjs \
            --mode both \
            --gas-limit 250000
        working-directory: tools/rewards
