name: GoReleaser

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    uses: sei-protocol/uci/.github/workflows/goreleaser-release.yml@v0.0.10
    with:
      go-version: '1.25.6'
      submodules: 'true'
      prebuild-script: |
        docker run --rm -v "$PWD":/src -w /src golang:1.25.6-alpine sh -c '
          apk add --no-cache build-base git &&
          git config --global --add safe.directory /src &&
          LINK_STATICALLY=true BUILD_TAGS=muslc LEDGER_ENABLED=false make build
        '
