name: GoReleaser

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    uses: sei-protocol/uci/.github/workflows/goreleaser-release.yml@v0.0.10
    with:
      go-version: '1.25.6'
      submodules: 'true'
      prebuild-script: |
        bash scripts/setup-zig-cc.sh
