name: Load Generator Image

on:
  push:
    branches:
      - main
    paths:
      - integration_test/load_generator/**
      - .github/workflows/load-generator-image.yml
  pull_request:
    branches:
      - main
    paths:
      - integration_test/load_generator/**
      - .github/workflows/load-generator-image.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5
      - name: Build load generator
        uses: docker/build-push-action@v6
        with:
          context: integration_test/load_generator
          file: integration_test/load_generator/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/sei-protocol/sei-load-generator:sha-${{ github.sha }}
          cache-from: type=gha,scope=sei-load-generator
          cache-to: type=gha,mode=max,scope=sei-load-generator
