name: Mock Balances Build Check

on:
  pull_request:
    branches:
      - main
      - release/**
  merge_group:
    branches:
      - main
      - release/**
  push:
    branches:
      - main
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  mock-balances-build:
    name: Compile with Mock Balances
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.6'

      - name: Build with Mock Balances
        run: make install-mock-balances
