  codex-review:
    name: Codex PR Review
    needs: [upload-coverage-report]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout PR HEAD (full history)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      - name: Compute merge-base diff
        run: |
          set -euo pipefail
          BASE_REF='${{ github.event.pull_request.base.ref }}'
          git fetch --no-tags origin "$BASE_REF":"refs/remotes/origin/$BASE_REF"
          MB=$(git merge-base "origin/$BASE_REF" HEAD)
          git diff --unified=0 "$MB"..HEAD > pr.diff
          git --no-pager diff --stat "$MB"..HEAD > pr.stat || true

      - name: Run Codex CLI (guarded with Slack)
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          MAX=${MAX_TOKENS:-6000}
          if ! codex pr \
              --diff pr.diff \
              --stat pr.stat \
              --pr-url "$PR_URL" \
              --pr-number "$PR_NUMBER" \
              --max-output-tokens "$MAX" \
              --slack; then
            codex pr \
              --diff pr.diff \
              --stat pr.stat \
              --pr-url "$PR_URL" \
              --pr-number "$PR_NUMBER" \
              --max-output-tokens "$MAX" \
              --no-guard \
              --slack
          fi
