name: Self-Hosted Runner Test

on:
  workflow_dispatch: # lets you trigger manually from GitHub UI
  push:
    branches:
      - main

jobs:
  check-runner:
    runs-on: [self-hosted, Linux, X64]  # matches your runner’s labels
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print environment info
        run: |
          echo "Running on self-hosted runner!"
          echo "Date: $(date)"
          uname -a
          lsb_release -a || cat /etc/os-release
          echo "Go version:"
          go version || echo "Go not installed"

      - name: Disk space check
        run: df -h

      - name: Print current directory
        run: pwd && ls -lah
