name: "\U0001F9E0 Codex Go Syntax Guard"

on:
  push:
    branches: [main, evm, evm1]
  pull_request:
    branches: [main, evm, evm1]
  workflow_dispatch:

jobs:
  go-syntax-check:
    name: "\U0001F9EA Codex Go Top-Level Syntax Check"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "\U0001F4E5 Checkout repository"
        uses: actions/checkout@v4

      - name: "\U0001F6E0\U0001F3FE Set up Go environment"
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: "\U0001F50D Detect top-level assignments ( := )"
        id: detect
        run: |
          echo "\U0001F50D Scanning go-ethereum/core/vm/ for invalid top-level := usage..."
          mkdir -p codex-logs

          BAD_LINES=$(grep -rPn '^[^/]*:=.*$' go-ethereum/core/vm/ | grep -v 'func' || true)

          if [[ -n "$BAD_LINES" ]]; then
            echo "$BAD_LINES" > codex-logs/codex_go_patch.log
            echo "::warning file=go-ethereum/core/vm/contracts.go::Top-level := assignments found!"
            echo "violation=true" >> $GITHUB_OUTPUT
          else
            echo "\u2705 No top-level syntax violations detected."
            echo "violation=false" >> $GITHUB_OUTPUT
          fi

      - name: "\U0001F6E0\uFE0F Auto-patch into init() (Codex assist)"
        if: steps.detect.outputs.violation == 'true'
        run: |
          FILE="go-ethereum/core/vm/contracts.go"
          INIT_BLOCK="// codex:init-wrap"

          echo "\U0001F6E0\uFE0F Applying auto-patch to $FILE"

          # Create init() if missing
          if ! grep -q "$INIT_BLOCK" "$FILE"; then
            echo -e "\nfunc init() {\n    $INIT_BLOCK\n}" >> "$FILE"
          fi

          # Move rogue := lines into init()
          sed -i.bak '/^[^/]*:=.*$/ {
            s/^/\/\/ Codex moved: /
            h
            s/^.*:=/    /
            G        
            s/\n/\n    /
            s/$/ \/\/ \u2190 auto-moved by Codex/
          }' "$FILE"

          echo "\u2705 Codex wrapped invalid lines into init() block."

      - name: "\U0001F4E4 Upload Codex patch log"
        uses: actions/upload-artifact@v3
        with:
          name: codex-go-syntax-log
          path: codex-logs/codex_go_patch.log
