name: Tests
on:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for describe/tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Test group 03
        run: |
          NUM_SPLIT=20
          make test-group-03 NUM_SPLIT=20

      - name: Test occ_tests (serial, no race)
        run: |
          make test-occ

