name: UCI

on:
  push:
    paths: [ 'version.json' ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  releaser:
    name: Release
    uses: sei-protocol/uci/.github/workflows/release-publish.yml@v0.0.2