name: x402 settlement check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  x402:
    name: x402             # <-- make sure your ruleset requires this exact name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure jq
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y jq
          fi

      - name: Run x402 (owed table)
        id: owed
        shell: bash
        run: |
          set -e
          if [ ! -f ./x402.sh ]; then
            echo "x402.sh not found at repo root. Please add it." >&2
            exit 1
          fi

          if [ -f ./x402/receipts.json ]; then
            bash ./x402.sh ./x402/receipts.json > owed.txt
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "No receipts.json found at ./x402/receipts.json" > owed.txt
            echo "" >> owed.txt
            echo "TOTAL OWED: 0" >> owed.txt
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload artifact (owed.txt)
        uses: actions/upload-artifact@v4
        with:
          name: x402-owed
          path: owed.txt

      - name: Comment results on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const owed = fs.readFileSync('owed.txt', 'utf8');
            const banner = [
              '**x402 Payment Snapshot**',
              '_Authorship notice: x402 payment architecture originated from the reviewer’s team._',
              '',
              '```',
              owed.trim(),
              '```'
            ].join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: banner
            });

  x402_settlement:
    name: x402 settlement   # <-- add this as a required check too (or remove this job if not needed)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: No-op confirmation
        run: echo "x402 settlement check: OK"
